### ISSUE TITLE
"Update Notepad++" does not work on Windows 2003 and older any more

### ISSUE THREAD

**Issue by vbrozik** [notepad-plus-plus/notepad-plus-plus#967]
I am using Notepad++ on Windows 2003 and when I select _Update Notepad++_ from the menu I see this pop-up:

> `---------------------------`
> curl error
> `---------------------------`
> schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - The message received was unexpected or badly formatted.
> `---------------------------`
> OK
> `---------------------------`

After some investigation I realized that Notepad++ has a separate tool GUP (Generic Updater) for updates. It uses libcurl.dll for HTTP/HTTPS communication.

It seems that old cipher suites which allowed system components on Windows 2003 and older to establish an SSL/TLS connection were removed from the configuration of the web server for https://notepad-plus-plus.org/ This means that any more you cannot access this URL using Internet Explorer or curl not accompanied by additional [SSL/TLS libraries](http://curl.haxx.se/docs/ssl-compared.html) (libcurl packed with GUP uses system's Schannel / Secure Channel).

See the results of the SSL/TLS scan: https://www.ssllabs.com/ssltest/analyze.html?d=notepad-plus-plus.org - interesting is the section Handshake Simulation.

You can also find interesting information regarding this problem in this curl issue:  [Cannot download from GitHub with curl 7.42.1 on Windows #267](https://github.com/bagder/curl/issues/267). As a result of the issue the new version of curl has a more useful error message than the one shown above.

Could you please add some suitable [SSL/TLS library](http://curl.haxx.se/docs/ssl-compared.html) to libcurl shipped with GUP so that it will work again on old MS Windows?

**Comment by riparap** [comment]
Are there any updates related to this? .. I would also appreciate solution to this problem. I know that Windows Server 2003 (as well as XP) are no longer supported by Microsoft but I would guess there still are plenty of these systems still in use so having easy way to upgrade notepad++ on these systems would be a great benefit.

**Comment by milipili** [comment]
The only solution to your problem seems to build libcurl with openssl (which takes some time to do it correctly). Any help appreciated :)

**Comment by pabouk** [comment]
Hello milipili, thanks for your message. Yes, as I wrote, libcurl has to be supplemented with a SSL/TLS library. (not necessarily openssl) Unfortunately I do not have a build environment for Windows but I can test the required parameters to build libcurl with openssl (or a different SSL library) on Linux. Would this help you? (I use Windows only occasionally.)

Now I see that this problem should be solved in the repository of WinGup: https://github.com/gup4win/wingup

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
