### ISSUE TITLE
Functional and operational recommendations

### ISSUE THREAD

**Issue by m1517** [notepad-plus-plus/notepad-plus-plus#9676]
Hello,
1. Automatically complete words. I hope to complete words only when I press the TAB key. When I press enter, I will enter the characters that have been entered on the screen, and hide the prompt bar. Or add a tab/enter option on the set an option;
Fully match also hide the prompt bar. Otherwise, the prompt bar will often block the line of sight.
![1](https://user-images.githubusercontent.com/42157457/111866058-99ed3180-89a5-11eb-83f8-845b484a02b0.jpg)
![2](https://user-images.githubusercontent.com/42157457/111866062-9fe31280-89a5-11eb-8125-6bcc8c265df0.jpg)

2. Add a shortcut key to insert the current system date and time.
3.  In multi instance mode, the same file can be opened many times, but the empty window can't open many times. I hope that the empty window can have multiple instances, and the same file can't be opened many times.

                        thanks !

OS: window7,  notepad++ v7.9.1(64bit)

**Comment by sasumner** [comment]
Notepad++ developers can't process feature requests where multiple items (that aren't at all very-related) are placed in one issue.  If you are inclined to put the effort in, please create separate issues for separate things.

Also, your "2" request has been requested before.  Please search for existing issues (whether "open" or "closed") before creating identical ones with the same topic.  The time/date insertion aspect has an accepted solution:  It is done via plugin and a script.  As an example, see https://community.notepad-plus-plus.org/post/44128

Also, your "3" request makes no sense.  When you write issues, you need to follow the template (that you ignored with this issue), creating a series of reproduction steps that clearly illustrates your point(s).  Your "1" request suffers from this as well.
