### ISSUE TITLE
[Feature Extension Request] Doc Switcher -- Additional column with full file path for sorting

### ISSUE THREAD

**Issue by f--g** [notepad-plus-plus/notepad-plus-plus#9679]
### Description of the Issue
Currently in Doc Switcher are two columns available "Filename" and "Extension" -- so the list can be sorted by filename and by extension (great feature btw).
It would be really helpful, when there would be a third (optional) column with the full file path.
Then sorting would be possible by filename, filepath and extension.

### Expected Behavior
Sorting all files in Doc Switcher by full file path when clicking in header row of the new "path" column.

![grafik](https://user-images.githubusercontent.com/5459684/111892112-99ca5180-89f8-11eb-8ad5-e1e4f60da57a.png)

**Comment by ArkadiuszMichalski** [comment]
Asking for path (instead extension) also arise here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4515.

@f--g You can try "Window Manager" plugin, but it's very old, only 32-bit and has some bugs:
https://sourceforge.net/projects/npp-plugins/files/WindowManager/

![image](https://user-images.githubusercontent.com/2730894/111938476-58a27200-8aca-11eb-931d-4c8f220daf4c.png)

**Comment by f--g** [comment]
Thanks @ArkadiuszMichalski for the reply -- I saw the other issue, but didn't see the line with the path suggestion.
I had a look the windowManager plugin -- I wanted to build it x64 myself. Beside a few errors with not declared variables -- I could not build a working 64Bit version. But I need to admit that I am not familiar with windows-API at all.

I think I will try to extend the DocSwitcher for myself and keep the issue/request open. Maybe it will be allowed to integrate the changes in future.
