### ISSUE TITLE
Add `-w,--wait` CLI argument that waits for the started notepad instance to exit before returning a status code

### ISSUE THREAD

**Issue by SirWindfield** [notepad-plus-plus/notepad-plus-plus#9680]
Starting the application by calling the CLI from a terminal starts the GUI but directly sends a success exit code inside the terminal.
The wait flag would allow one to wait until the user closes the GUI and only then send an exit code, making the terminal block as long as the GUI is open.

Other editors have the same feature:
- `atom --wait`
- `subl -w`
- `code -w`
- `open -W` on macOS (generic opening tool, pre-installed).

**Comment by sasumner** [comment]
One can use a feature of the operating system for this, e.g. from cmd.exe,

`start /wait notepad++.exe`

**Comment by nikitalita** [comment]
> One can use a feature of the operating system for this, e.g. from cmd.exe,
> 
> `start /wait notepad++.exe`

No, this doesn't work. I've attempted `start /wait` it in many different configurations, it still doesn't block and immediately returns.

**Comment by sasumner** [comment]
>No, this doesn't work. 

A very simple test that I did shows that it DOES work.
It would be interesting to know your setup where it doesn't work.
