### ISSUE TITLE
Function List languages have gone missing

### ISSUE THREAD

**Issue by gnodarse** [notepad-plus-plus/notepad-plus-plus#9698]
### Description of the Issue
Languages which used to have their functions appear in the Function List have gone missing, or at least Rust no longer has support for navigating to functions via Function List

### Steps to Reproduce the Issue
1. Open up or create a file with .rs extension
2. Make sure that a correctly defined function is in the file
3. Save the file
4. Observe that the function does not show up on the Function List

### Debug Information
Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1909
OS Build : 18363.1440
Current ANSI codepage : 1252
Plugins : mimeTools.dll nppAutoDetectIndent.dll NppConverter.dll NppExport.dll NppMarkdownPanel.dll NppTextViz.dll 

### Other info
I am certain that Rust used to be supported. A Rust file I've been working on no longer has its function's appear. I believe that the version I was using before was 7.9.1.

![image](https://user-images.githubusercontent.com/46761795/112368340-59492d00-8cb1-11eb-9aab-77a9dc0479cf.png)
![image](https://user-images.githubusercontent.com/46761795/112368371-636b2b80-8cb1-11eb-9b41-6c88f0cfca0a.png)

**Comment by chcg** [comment]
See https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9592.
There is no support for autocompletion and functionlist for rust. Rust is autodetected for extension .rs .

What is possible is to switch to a similar language like C or C++ and then have the functionlist, but then the wrong lexer is used and the syntax highlighting might be not accurate.

![grafik](https://user-images.githubusercontent.com/12630740/112434156-83e3c600-8d43-11eb-96a1-4a099d5705a6.png)

Maybe you also did some own modification which are overwritten by the update.

**Comment by gnodarse** [comment]
I checked and the language is being set correctly to Rust for the .rs extension. Thanks for the idea for using C/C++ for function list, but syntax highlighting is not something I'm willing to give up.

I did have a custom Rust function list extension I made for myself at some point when I was less busy. Maybe I'll try setting it up again.

**Comment by ArkadiuszMichalski** [comment]
Try [portable version](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-the-latest-release-portable-version-of-notepad), if works you have some old config file (probably `langs.xml`).

**Comment by gnodarse** [comment]
Thank you for the help. I'll just try creating a quick usable parser for rust functions.

**Comment by chcg** [comment]
@gnodarse  See PR#9727, with a first simple version, which you might want to extend. Maybe you could also check the corresponding unittest file for missing rust syntax examples.
