### ISSUE TITLE
New document name is using two spaces

### ISSUE THREAD

**Issue by Rikk** [notepad-plus-plus/notepad-plus-plus#97]
Npp is creating new blank files with two spaces in name: "new&nbsp;&nbsp;1"

I could track a possible cause of this to the `newEmptyDocument()` function of https://github.com/donho/notepad-plus-plus/blob/master/PowerEditor/src/ScitillaComponent/Buffer.cpp#L1089 but I'm not sure.

Maybe changing
`wsprintf(nb, TEXT(" %d"), nextUntitledNewNumber());`
to
`wsprintf(nb, TEXT("%d"), nextUntitledNewNumber());`
would fix it?

**Comment by milipili** [comment]
A PR #140 has been provided.

**Comment by Rikk** [comment]
Thanks @milipili & @donho

**Comment by Rikk** [comment]
"new&nbsp;&nbsp;0" still has two spaces...
Maybe same change is also needed on [line 1109](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/ScitillaComponent/Buffer.cpp#L1109).
Ref: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/183

**Comment by milipili** [comment]
The issue has not been fully resolved. copy/paste from #183: @ Eldaw 

> PR 140 changed 1 line of code in Notepad++ v6.7.9 in order that new files such as 'new 1', 'new 2', 
> etc. only have 1 space in their name rather than 2.
> #140
>
> But this only partially fixed the issue. The first file that gets automatically created when launching a fresh instance of Notepad++, 'new 0.txt' still has 2 space in its name.
