### ISSUE TITLE
Notepad++ compatibility with Windows XP

### ISSUE THREAD

**Issue by kacper6768** [notepad-plus-plus/notepad-plus-plus#9709]
What is the latest version of Notepad++ compatible with Windows XP?

**Comment by mere-human** [comment]
It is listed in the [README#supported-os](https://github.com/notepad-plus-plus/notepad-plus-plus#supported-os) and also here [SUPPORTED_SYSTEM.md](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/SUPPORTED_SYSTEM.md)

**Comment by sasumner** [comment]
@kacper6768 
In the future, please ask questions [HERE](https://community.notepad-plus-plus.org/).
