### ISSUE TITLE
Duplicated words in Auto-Completion pop-up window

### ISSUE THREAD

**Issue by rddim** [notepad-plus-plus/notepad-plus-plus#9711]
### Description of the Issue

When using the `Auto-Completion` function some words are duplicated.
### Steps to Reproduce the Issue

1. Download a fresh portable version of Notepad++
2. Make sure the `Word completion` is selected in `Settings` > `Preferences...` > `Auto-Completion`
3. Open the `english.xml` or `bulgarian.xml` file from `localization` folder of Notepad++
4. Start to type `iss` or `it` in `english.xml` or `прое` in `bulgarian.xml`

### Expected Behavior

I expect to see not duplicated words in the pop-up window
### Actual Behavior

In the test case when type `iss` or `it` in `english.xml` the word `it` is duplicated. Same is the word `them` when type `the`. In `bulgarian.xml` the word `проекта` is duplicated when type `прое`. Same is the word `права` when type `пра`. I use `bulgarian.xml` for test the cyrillic.
### Debug Information

```
Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Users\Home\Downloads\npp.7.9.5.portable.x64\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1251
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
```

![npp-acmplt](https://user-images.githubusercontent.com/8998791/112754242-d8a56c00-8fe3-11eb-8b17-635fed92c4fa.gif)

**Comment by Uhf7** [comment]
Easier way to reproduce:
- New text buffer
- Type `abc abc? abc`

Can be fixed by including a `?` next to the `!` in this line:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/09d6241686d650c22d39ae8742cc2544aac7dcc8/PowerEditor/src/ScintillaComponent/AutoCompletion.cpp#L149
