### ISSUE TITLE
Loud Beep sound after dragging to dock/undock the floating panel.

### ISSUE THREAD

**Issue by KnIfER** [notepad-plus-plus/notepad-plus-plus#9712]
### Steps to Reproduce the Issue

1. Open Function List And Document Map, dock them together.
2. Drag on the caption. 
3. Keep trying docking and undocking

### Expected Behavior
/

### Actual Behavior
Heard unexpected beep

### Debug Information
```
Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : D:\Code\FigureOut\Textrument\秘籍\npp.7.9.5.portable\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Home (64-bit) 
OS Version : 1909
OS Build : 18363.1440
Current ANSI codepage : 65001
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
```

### Recorded a video  :

https://user-images.githubusercontent.com/11593903/112755356-415c0b00-901b-11eb-812e-02871c31f2a7.mp4

**Comment by mere-human** [comment]
@KnIfER Try checking with _Mute all sounds_ preference ON:
![image](https://user-images.githubusercontent.com/9664141/112755752-ced33700-8fea-11eb-95d9-3ccda4e7d451.png)

**Comment by sasumner** [comment]
@KnIfER Is there something else that you see for the docking/undocking features in this instance?  Otherwise, suggest ignoring the beep.

**Comment by KnIfER** [comment]
@mere-human **Mute all sounds** doesn't help.

**Comment by KnIfER** [comment]
what's the cause ?

**Comment by KnIfER** [comment]
related to `_vContainer[iContSrc]->removeToolbar(TbData)`

**Comment by KnIfER** [comment]
cause: 
```
void DockingCont::selectTab(int iTab)
{
...
     ::SetFocus(((tTbData*)tcItem.lParam)->hClient);
}
```

beep on SetFocus

**Comment by KnIfER** [comment]
No one can reproduce? Is lt just my device's fault?

**Comment by mere-human** [comment]
> No one can reproduce? Is lt just my device's fault?

I've just tried in 8.1.2 and I can't reproduce it.

Notepad++ v8.1.2   (64-bit)
Build time : Jul 16 2021 - 01:59:50
Path : C:\Program Files\npp-portable\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1110
Current ANSI codepage : 1252
Plugins : CodeAlignmentNpp.dll ColumnTools.dll DSpellCheck.dll HexEditor.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExport.dll NppMarkdownPanel.dll XMLTools.dll
