### ISSUE TITLE
Three text contextual options are not localized

### ISSUE THREAD

**Issue by Patriccollu** [notepad-plus-plus/notepad-plus-plus#9713]
Hello,

I just noticed that three text contextual options are not localized: "Style token", "Remove style" and "Plugin commands".

In the screenshot below, you can see that everything is translated in Corsican except these three options.

![Notepad++ Two text contextual options are not localized](https://user-images.githubusercontent.com/22452654/112755456-10f77b00-8fe1-11eb-9347-9bad911e38fe.png)

In the Search menu, two options - `Mark All` > `Using 1st [to 5th] Style` and `Unmark All` > `Clear 1st [to 5th] Style` - are similar to the first two above and properly localized.

Thanks,
Patriccollu.

**Comment by sasumner** [comment]
Sub-menu names like this in context menu are not localized because they are set via the "FolderName" property in `contextMenu.xml`.  The best suggestion might be to customize your context menu in this regard.  Choose _Settings_ menu > _Edit Popup ContextMenu_ and search for `FolderName`.

**Comment by Patriccollu** [comment]
@sasumner Thanks for your answer, I will try. Cheers, Patriccollu.

**Comment by sasumner** [comment]
Reopening in case there's interest in working on it.
@donho provided some advice about it here: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9684#issuecomment-809744046

**Comment by Patriccollu** [comment]
@sasumner 
Hello,

I tried using the circumvention advocated by Don, i.e: using `subMenuId` instead of `FolderName`
It works but the menu is far bigger as all (sub)options are expanded:

![contextMenu using subMenuId](https://user-images.githubusercontent.com/22452654/113031933-8f921b00-918f-11eb-9d76-ea32eb61b1f9.png)

But this globally answers to my need as there is not any localization in contextMenu.

Cheers,
Patriccollu.

**Comment by Patriccollu** [comment]
In summary, the two options require to modify contextMenu:

1. using `subMenuId `instead of `FolderName`, no need of any translation but the display is larger (see previous comment)
2. using `FolderName` with translations, the display of options in contextMenu is correct (see screenshot below)

![contextMenu with translation in FolderName](https://user-images.githubusercontent.com/22452654/113071782-c2ef9c80-91c5-11eb-9f7f-405dd876d6b7.png)

The display is correct but it's a pity to _translate some strings which are already translated_ in the language `.xml` file.

This is frustrating because the other entries using `MenuEntryName` and `MenuItemName` (see below) are properly processed and don't need any translation in contextMenu.

![contextMenu with entries using MenuEntryName](https://user-images.githubusercontent.com/22452654/113073334-3050fc80-91c9-11eb-9ea6-366619cae82d.png)

Thanks @sasumner for your help and explanations. I understand that you are not interested in working more on this issue.

**Comment by Patriccollu** [comment]
@sasumner Thanks for this clarification.

Actually I misunderstood Don's comment in the other PR 9684 when he wrote: "_User can use subMenuId instead of FolderName then the text of menu entry will be from the (translated) application instead of provided string_."

I thought this attribute could already be used! :-(

**Comment by Patriccollu** [comment]
@sasumner @donho @ArkadiuszMichalski 
Hello,

I'm closing this issue by now. We will see in the future if someone else is interested in implementing this feature.

Thanks for your comments,
Patriccollu.

**Comment by ArkadiuszMichalski** [comment]
When you close this issue, you are signaling not to work on it, rather than work on it. I have always disliked those default untranslated contextual submenu entries. Currently, they require manual adjustment for everyone, which does not seem like the right approach. Additional IDs for these default submenus would solve the problem, for others everyone could already use native names.

**Comment by Patriccollu** [comment]
@donho @ArkadiuszMichalski 
Thanks a lot to both of you for your work on this issue. Patriccollu.
