### ISSUE TITLE
Switching the encoding via keyboard shortcut disregards the default tab width

### ISSUE THREAD

**Issue by sesom42** [notepad-plus-plus/notepad-plus-plus#9716]
### Description of the Issue
Selecting a different encoding with a keyboard shortcut briefly switches to the default tab width. The default tab width is not displayed correctly again until switching between tabs.

### Steps to Reproduce the Issue
1. set default tab size to 4

![Notepad++ set default tab size](https://user-images.githubusercontent.com/8649051/112802970-1a312800-9073-11eb-8aab-55a25068b73a.png)

2. configure a new shotcut to switch to different encoding

![Notepad++ switch character set shortcut](https://user-images.githubusercontent.com/8649051/112803088-359c3300-9073-11eb-94ae-7c0c29cd07db.png)

3.  open a file with different encoding

![Notepad++ open encoded text file](https://user-images.githubusercontent.com/8649051/112803264-63817780-9073-11eb-8591-95d020cadc16.png)

4. press the configured shortcut to switch the encoding

![Notepad++ press shortcut](https://user-images.githubusercontent.com/8649051/112803348-785e0b00-9073-11eb-963e-b0bf8d4bb5aa.png)

### Expected Behavior
Displayed tab size should not change if character encodings are switched.

### Actual Behavior
The configured default tablulator size is temporarily ignored.

### Debug Information
Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19042.867
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment]
Anyone can reproduce this?

**Comment by sesom42** [comment]
> Anyone can reproduce this?

A colleague of mine has the same issue on his PC.

**Comment by sesom42** [comment]
The error no longer occurs. At least since version 8.1.1. Apparently another change led to the cleanup of the error.
