### ISSUE TITLE
Feature Request - Improved Modern UI

### ISSUE THREAD

**Issue by Seranok** [notepad-plus-plus/notepad-plus-plus#972]
More than one year has passed since my usage of notepad++, yet there is not UI update. I mean  windows 10 released and notepad++ still doesnt have an UI update. I would like very much to see an UI update, don't know if its me. But yet Im saying WinRAR existed for than 10 years now its overtaken by a modern B1 Archiver. So Im waiting for a good reply. Suggestion and votes are recommended.
Just let the developers know that not only coders use notepad++ but also gamers and HTML editors.
Thanks.

**Comment by didsun** [comment]
+1

**Comment by Croydon** [comment]
That's a duplicate of #622 und should be closed. Please use the search next time.

**Comment by Seranok** [comment]
Gladly, However thank you for pointing out the issue. Guess Im not the only one.

**Comment by tommiehansen** [comment]
I did a mockup before on how **i would style** a new NP++.

**NEW**
![new](http://i.imgur.com/FqKopcM.jpg)

**OLD** (custom style)
![new](http://i.imgur.com/i0adi2H.jpg)

The new version is basically a merge of UI styles from Spotify, Githubs Atom.io editor and Notepad++.
Of course this darker version shouldn't be mandatory. A simple checkbox should take care of that "issue".

**Comment by ikoshura** [comment]
I made a Fluent UI theme for Notepad++, I used the VS Code color scheme along with the Windows 11 Mica effect. You can take a look at my theme over here: https://github.com/ikoshura/Fluent-Npp

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/100127946/0bcb696d-9b15-4c17-bfe6-7a063af3094c)

**Comment by alankilborn** [comment]
@ikoshura See https://github.com/notepad-plus-plus/nppThemes
