### ISSUE TITLE
File history bug

### ISSUE THREAD

**Issue by jokbon** [notepad-plus-plus/notepad-plus-plus#9720]
### Description of the Issue
I changed tab history settings.
Notepad++ still displays history how it wants.

### Steps to change history settings
1. Open first notepad instance.
2. Settings
4. Preferences
5. Recent files history
6. Limit history

### Steps to Reproduce the Issue
1. Open first notepad instance.
2. Close first instance
4. Open another first notepad instance
5. Tab got file history, this shudnt happen.

**Comment by sasumner** [comment]
Closing due to lack of information or understandability of information.  If you can clarify, and follow the issue template better (include _Debug Information_) we will consider reopening.
