### ISSUE TITLE
Horizontal scrolling with mouse wheel not working (neither in doc, nor on tabs)

### ISSUE THREAD

**Issue by V1pr** [notepad-plus-plus/notepad-plus-plus#9721]
I've a logi mouse with 2 wheels, both works ok in other apps. However, in NP++, the horizontal scrolling is not working.

- when a document is active (window is also active) and I start to scroll (horizontally), the scrollbar changes apperance, the "box" moves on the scrollbar, but the document doesn't.
- it does not matter if I select a (another) tab and then scoll, or just the pointer is above the tabs, the horizontal scroller does not do anything (the vertical wheel scrolls the tabs, so this it not a big deal)

### Steps to Reproduce the Issue
1) Have a mouse with vertical scrolling capabilities
2) write a line longer than screen
3) scroll with the horizontal wheel

### Expected Behavior
The document should be scrolled as well, not just the scrollbar

### Debug Information
Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1440
Current ANSI codepage : 1250
Plugins : AnalysePlugin.dll ComparePlugin.dll DSpellCheck.dll mimeTools.dll nppAutoDetectIndent.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll Tidy2.dll

Screenshots:
1) before scrolling with the wheel:
![image](https://user-images.githubusercontent.com/26622930/113127983-9ebdab00-9219-11eb-8113-07b36a6692c4.png)

2) after scrolling with the wheel (you can notice the scrollbars original position):
![image](https://user-images.githubusercontent.com/26622930/113128158-cd3b8600-9219-11eb-8fb9-d74c6ff323dd.png)

**Comment by sasumner** [comment]
There are already a few such issues on this topic.  Please find one of those and add any relevant comments there.
