### ISSUE TITLE
Suggestion: Make Notepad++ a restartable Windows 10 application

### ISSUE THREAD

**Issue by jcrmatos** [notepad-plus-plus/notepad-plus-plus#9722]
Consider making Notepad++ a restartable Windows 10 application.

The opposite of this article
https://www.howtogeek.com/396884/how-to-stop-windows-10-from-reopening-your-previous-applications-after-restarting-your-pc/

**Comment by rimrul** [comment]
> > https://docs.microsoft.com/en-us/windows/win32/recovery/registering-for-application-restart

That seems to be only for restarting an application after a crash. (Like Windows explorer does)

**Comment by HarelM** [comment]
>Note for application installer authors: Registering for application restart will also cause Windows to automatically restart the application after the computer is restarted in cases where the computer is restarted due to a software update. For this to work, the installer of the application must call the [ExitWindowsEx](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-exitwindowsex) function with the EWX_RESTARTAPPS flag set or the [InitiateShutdown](https://docs.microsoft.com/en-us/windows/desktop/api/winreg/nf-winreg-initiateshutdowna) function with the SHUTDOWN_RESTARTAPPS flag set.

**Comment by HarelM** [comment]
Great!! Thanks!!
