### ISSUE TITLE
Cannot spawn another instance of Notepad++ for an empty non-saved document tab

### ISSUE THREAD

**Issue by jringbox** [notepad-plus-plus/notepad-plus-plus#9724]
### Description of the Issue
Cannot spawn another instance for a new document tab that have never been saved.

### Steps to Reproduce the Issue
1. Open Notepad++ with other documents open in tabs.
2. Click "File -> New".
3. Drag the new tab off Notepad++ to spawn another shell.  It doesn't work.

Workaround is to type something, save the document as new.txt or whatever, and drag that tab off Notepad++.   Then, a new notepad++ will be spawned but the document had to be saved first.

### Expected Behavior
A new spawned Notepad++ with new empty non-saved tab.

Alternatively, the File menu could have a menu option to spawn a new Notepad++ with an empty non-saved tab.

### Actual Behavior
Notepad++ does not allow spawning another Notepad++ for a non-saved new document tab.

**Comment by sasumner** [comment]
Current behavior is by-design and isn't judged to be important enough to change.  Sorry.

**Comment by jringbox** [comment]
I didn't realize and just found out that I can go to "Run->Open Another Instance".  That's good enough for me.  :)

**Comment by sasumner** [comment]
The _Run_ menu's _Open file in another instance_ , while enabled in the described situation, will not open the same "new" buffer in the second instance (meaning the contents will not be carried over).

Somewhat interestingly, if invoked from this situation:

![image](https://user-images.githubusercontent.com/30118311/113413662-2e359c00-9389-11eb-949e-158feee7049b.png)

It results in this when the second instance starts:

![image](https://user-images.githubusercontent.com/30118311/113413688-3988c780-9389-11eb-8f2d-754f43999856.png)

**Comment by jringbox** [comment]
Funny.  We closed the issue but it seems there's an interesting "feature" that exists though I would perceive that as a bug personally.  Apparently, it takes whatever text your cursor is on the editor and tries to create a document for that text.  Interesting.  If you're on a blank line line then it doesn't prompt since the cursor is not next to text.  I'd enter a bug but I'm afraid I'll get shot down for it.  So I'll skip it.  At least the user can respond to the prompt and click "No" on creating the file.

**Comment by sasumner** [comment]
@jringbox It is just a configuration bug with `shortcuts.xml`.  You can edit that file and remove `$(CURRENT_WORD)` from the affected command, in your current Notepad++.  I will attempt to do it on a more permanent basis.

>I think that feature is for a readme.txt file where a list of files might be in the text file. While on the line you can do "Open in Another Instance" to open that document, I guess.

Maybe...but that relies on a lot of foreknowledge for a user to have about how it would work.  I don't like it.
