### ISSUE TITLE
Notepad++ Freezing 

### ISSUE THREAD

**Issue by jturner77** [notepad-plus-plus/notepad-plus-plus#973]
I have been using Notepad++ for a couple months now and have not had any issues. This past week though has changed. Every time I try and save a file or save all the files the app freezes and will not respond. I have to open Task Manager to get it to close. Then when I try and reopen it it will not load. It will work for a little bit after I restart my computer, but even if I try and close the program by the X in the left corner it will freeze up and not respond. Right now it is frozen. I tried to save and it froze. It also freezes sometimes when I try and open files, and when I look in the menu like file, edit, window, ?. I really do love this app. Please someone fix it.

**Comment by dail8859** [comment]
Have you tried disabling all of your plug-ins? Are the files you edit on a network drive? More information would be appreciated.

**Comment by jturner77** [comment]
I just reinstalled the latest version of Notepad++.  I am using Windows 10, and I was saving the files to my hard-drive. I have not disable any plug-ins.

**Comment by dail8859** [comment]
I'd suggest disabling your plugins first. You can do this by renaming your `plugins` folder to something else temporarily before starting Notepad++. This will at least determine if it is a plugin issue or Notepad++ itself.

**Comment by donho** [comment]
@jturner77 Could you provide us your plugin list?

**Comment by dail8859** [comment]
@donho Side note: In cases like this #694 would be quite handy ;)

**Comment by donho** [comment]
@dail8859 Indeed. I'll implement it.

**Comment by donho** [comment]
closed due to lack of information.

**Comment by chtof** [comment]
Thank you Indranil-Banerjee, thanks to your post, I have created again the %LOCALAPPDATA%/Temp/N++RECOV and it solves my issue.
**But it would be nice if Notepad++ create this folder if needed on startup.**
