### ISSUE TITLE
set  Shift+DEL as a shutcut for  delete current line

### ISSUE THREAD

**Issue by alongL** [notepad-plus-plus/notepad-plus-plus#9731]
now the Shift+DEL  is default set to  SCI_CUT to perform cut.   There is Ctrl+X to do this work. No need to set another shutcut.

delete current line is  offen used .  
We can  set  Shift+DEL to SCI_LINEDELETE  as  default  configuration.
Is'n it?

**Comment by sasumner** [comment]
Default configuration has long been established.
Shortcut Mapper allows changing of assigned keycombinations.
