### ISSUE TITLE
Line Operations->Split Lines always uses the right-most specified Vertical Edge

### ISSUE THREAD

**Issue by sjcoo** [notepad-plus-plus/notepad-plus-plus#9736]
### Description of the Issue

In Notepad++ version 7.9.5 (Windows 10 pro v 20H2), I find that Split Lines (CTRL-I) always uses the right-most specified Vertical Edge when splitting lines, regardless of the editor window size.

This differs from the User Manual description: "Split Lines: will insert a line-ending into a long line(s) at the current size of the editor window or, if enabled, the right-most specified Vertical Edge (requires 7.9.3 or later), **whichever is less**." [emphasis added]

### Steps to Reproduce the Issue

1. Enable a vertical edge (for example, 70) in settings->Preferences->Margins/Border/Edge

2. Place caret/cursor on a line longer that the rightmost vertical edge (or select several lines)

3. Make the width of the current editor window less that the rightmost vertical edge position (for example, 50)

4. Enter CTRL-I to split selected line(s)

5. Increase the width of the current editor window to observe where line(s) was(were) split

### Expected Behavior

I expected line(s) to be split as determined by the width of the current editor window, because it is less that the rightmost vertical edge 

### Actual Behavior

Line(s) split as determined by rightmost vertical edge

### Debug Information

Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.868
Current ANSI codepage : 1252
Plugins : CLRTabsToSpaces.dll ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll

**Comment by sasumner** [comment]
If one returns to the 7.8.5 era, where there was a single vertical edge possible, and turns that edge on, splitting of lines is ALWAYS done using that vertical edge, even if the window width is less.

So, as 7.9.3 restored the edge splitting capability that was lost after multiple edges were introduced in 7.8.6, I believe the intent was to simply bring the functionality back with the old capability (but tied to the right-most edge).

Thus, I'd consider this current issue to be one of an error in the documentation.
But, it could also be viewed as a feature request.

**Comment by sasumner** [comment]
Since we didn't hear back from the OP about wanting this to be a feature request, let's close it out by correcting the bug in the documentation.  I'll create that issue.
