### ISSUE TITLE
Bug with && in <script> (php or html files)

### ISSUE THREAD

**Issue by martinmcbride** [notepad-plus-plus/notepad-plus-plus#974]
V 6.8.3

Editing a PHP or HTML file containing embedded JS. If the JS code contains a logical and operator (&&) it displays as 2 spaces instead of && (ie, the && is invisible).

The file itself is correct, the problem is with the way Notepad displays it.

**Comment by h-h-h-h** [comment]
Reference: issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/729

**Comment by dail8859** [comment]
Duplicate
