### ISSUE TITLE
can you please return previous sentence about notepad++ in its installer file?

### ISSUE THREAD

**Issue by zahra21** [notepad-plus-plus/notepad-plus-plus#9744]
hello every one.
first, i really appreciate your great program.
i believe that notepad++ is the best.
my laptop is not powerful, my laptop is from 2006 and i cant use office programs.
instead, i use notepad++ for everything which i wish to write and save.
i really love your great program and i pray sincerely for you and appreciate your great work.
i love windows xp and installed the last version which supports my favorite windows, (notepad++ version 7.9.2).
i am Muslim and i became very sad when i realized the new sentence in notepad++.
i tested various versions and i realized that if i want to use a version of notepad++ that has not the new sentence which made me very sad, i should stick to version 7.8 forever and never update because i want both compatibility with windows xp and having previous sentence about notepad++ which i like and i am glad to read it.
my favorite sentence is:
The best things in life are free. Notepad++ is free. So Notepad++ is the best.
this sentence is present in version 7.8 and many of previous versions in installer file.
but, unfortunately, i downloaded 7.8.1 and newer versions until 7.9.5 and i became very sad when i read the new sentence!
please, i sincerely request that you return my favorite sentence in notepad++ especially in version 7.9.2 and even newer versions that other people use.

**Comment by sasumner** [comment]
Noted.

**Comment by zahra21** [comment]
its the request which i wanted to be implemen in notepad++ and i mentioned that notepad++ is really great, but i have just a request about notepad++ in the ticket 9678 if i remember its number correctly.
should i use 7.8 forever to both have my favorite sentence and compatibility with xp?
or, is it possible that developers return my favorite sentence in 7.8.1 and newer ones especially 7.9.2 which is the last version compatible with windows xp?

**Comment by zahra21** [comment]
after further discovering and working with different versions of notepad++, i realized that
i need at least one or two new features or bug fixes in notepad++ 7.9 and 7.9.1 if 6133 really works.
so, can you please accept my request?
it is very easy and i am sure that you dont need many times to do this for me.
if 6133 works, i need 7.9.1 forever.
if does not work,
7.9 is enough for me forever.
because it has one new feature that i really need.
adding some searching options in preferences!

**Comment by zahra21** [comment]
i realized that:
notepad++ 7.9.1 is enough for me forever.
please accept my request in this version at least.
instead of the new sentence which made me very sad, please replace new sentence with previous sentence which i really love and believe in the installer and uninstaller file of notepad++ version 7.9.1
The best things in life are free. Notepad++ is free. So Notepad++ is the best

**Comment by zahra21** [comment]
my expected behaviour is that i read:
The best things in life are free. Notepad++ is free. So Notepad++ is the best.
in notepad++ installer and uninstaller file.
but i am glad that even if i read donho name.
if you do this for all versions its very excellent, but for myself,
after reading tens of issues which are solved in notepad++, i realized that
i dont need many new features, changes and bug fixes in newer versions.
version 7.9.1 is enough for me and its the best version for me forever.
because of the fix for 6133
that prevents data loss and file corruption which is the most important bug fixes i believe.
and some other changes that i need.
without this, i should use 7.8 forever, and i really need 6133 and some other fixes in newer versions especially about the new setting in misc that i can set notepad++ that always appends extension .txt in to my files which is added in 7.9.1
i am sure that fulfilling my request does not need time more than five minutes!

**Comment by sasumner** [comment]
@zahra21 What you're doing now is called "spamming the issues list".  People have recently been banned from the project for doing that.  You've made your request, you should leave it at that.

**Comment by zahra21** [comment]
> 
> 
> @zahra21 What you're doing now is called "spamming the issues list". People have recently been banned from the project for doing that. You've made your request, you should leave it at that.

but you closed this issue and nobody dont see closed issue and did not response me or help me that how can i use my favorite version?
because several times, i saved my files in notepad++, notepad++ did not append txt extension and the result was windows cant open this file dialog.
now i am very glad that this issue is solved in 7.8.7 and themn in version 7.9.1 by adding one option in preferences and misc
i really need version 7.9.1 and wish to install and use it immediately.
and as i said, i believe that it needs only less than five minute that i can use my favorite version!
