### ISSUE TITLE
Appearence of "dot" changes based on characters much later on line

### ISSUE THREAD

**Issue by AJNeufeld** [notepad-plus-plus/notepad-plus-plus#9747]
### Description of the Issue
In a UTF-8 encoded document, an encoding for a middle dot `e2 8b 85` is displayed properly when followed on the same line with a minus sign `82 88 92`.  When the minus sign is not present, the dot is instead displayed as a empty box.  A different minus sign character (`2d`) does not cause the dot character to appear.

### Steps to Reproduce the Issue
1. Open attached [`dot-to-box.xml.txt`](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6280389/dot-to-box.xml.txt) file.
2. Delete the minus sign on line 3.
3. Type the `-` character to add it back in.

### Expected Behavior
Appearance of dots should not changed based on other characters on the same line.

### Actual Behavior
Removing the minus sign causes the dots to change to boxes.
Adding a different minus sign character does not revert the boxes to dots.

![image](https://user-images.githubusercontent.com/16822261/114069490-a954f180-9864-11eb-9d20-32abfe176169.png)

### Debug Information
Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.1440
Current ANSI codepage : 1252
Plugins : HexEditor.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll XMLTools.dll

**Comment by sasumner** [comment]
Try this setting activated, if not already active:

![image](https://user-images.githubusercontent.com/30118311/114077693-11f89a00-9876-11eb-8cef-3a204d5f09f4.png)

**Comment by sasumner** [comment]
My testing shows DirectWrite solves the issue.
Closing, will reopen if it doesn't solve it for everyone.
