### ISSUE TITLE
Find/Replace regex missing digits

### ISSUE THREAD

**Issue by renatoskmail** [notepad-plus-plus/notepad-plus-plus#9750]
### Description of the Issue
**Find/Replace Regex is missing digits on group 3**

### Steps to Reproduce the Issue
1. Find what: **^(ID;\d+;Date;)(\d{4}|nodate)(?:(?!ID).)\*(\d{1,},\d{2})\s\*(Total)**
2. Replace with: **\1\2>\3\4**
3. Select "Regular expression". 
4. Check ". matches newline".
5. Select "Replace all".

### Expected Behavior
ID;1;Date;2021>43,21Total
ID;2;Date;
Notes1
Notes4
ID;3;Date;2019
ID;4;Date;nodate>123,45Total

### Actual Behavior
ID;1;Date;2021>3,21Total
ID;2;Date;
Notes1
Notes4
ID;3;Date;2019
ID;4;Date;nodate>3,45Total

![image](https://user-images.githubusercontent.com/32958383/114197310-96a3f080-9928-11eb-882a-93036e9f67e8.png)

### Debug Information
Notepad++ v7.9.4   (64-bit)
Build time : Mar 15 2021 - 01:03:10
Path : C:\Users\ruser1\Documents\notePLUS_64\notepad64++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.997
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll 

Input file:

ID;1;Date;2021
Notes1
Notes2
43,21 Total
ID;2;Date;
Notes1
Notes4
ID;3;Date;2019
ID;4;Date;nodate
Notes1
Notes3
Comments
123,45 Total

**Comment by sasumner** [comment]
Suggest changing your regular expression to the following to achieve your "expected result":

`(?s)^(ID;\d+;Date;)(\d{4}|nodate)(?:(?!ID).)*?(\d{1,},\d{2})\s*(Total)`

Note the insertion of the rightmost `?` in the new expression.

Suggest for future such "issues" that you more fully debug your regular expression, or you pose it as a question on the Community site:  https://community.notepad-plus-plus.org/

**Comment by renatoskmail** [comment]
OK, thank you !

Sorry about the mess.
