### ISSUE TITLE
Throwing Plugin exception "DSpellCheck"

### ISSUE THREAD

**Issue by aiqb05** [notepad-plus-plus/notepad-plus-plus#9752]
### Description of the Issue

In my test file I have lines which extend the screen width. "Word Wrap" option is disabled.
When I scroll right the window, following exception is thrown:

---------------------------
Plugin Exception
---------------------------
An exception occurred due to plugin: DSpellCheck.dll

Exception reason: vector<T> too long
---------------------------
OK   
---------------------------

### Steps to Reproduce the Issue

1.  Disable Word Wrap option
2. open a large folder as "Workspace"
3. Add few lines in a text file whose length extends the current screen width
3. Perform "scroll right" operation by clicking on the horizontal scroll bar at the bottom

### Actual Behavior

No exception shall be thrown. 
### Debug Information

Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1440
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

![image](https://user-images.githubusercontent.com/39417906/114235225-4f097d00-9999-11eb-944f-629de188f66c.png)

**Comment by sasumner** [comment]
DSpellCheck is not a Notepad++ supported plugin.
You should find where it is supported and file your issue there.

**Comment by chcg** [comment]
@aiqb05 DspellCheck is available at https://github.com/Predelnik/DSpellCheck. Maybe you should first check if you are using already the latest version 1.4.20.
