### ISSUE TITLE
Computer shutdown might results in loss of session data.

### ISSUE THREAD

**Issue by mzso** [notepad-plus-plus/notepad-plus-plus#9756]
### Description of the Issue

Had a bad experience today. Shutdown was halted, by np++ prompt that asked me whether I want to save a file that doesn't exist anymore (removed by another program) or not. Suspiciously only that file was present. I chose to not save and then I re-initiated the shutdown.
The next time I opened np++ no files were opened, even though I should have had several.
### Steps to Reproduce the Issue

The description covers it

### Expected Behavior
Either don't ask, or don't ask but don't lose the session.
Np++ doesn't ask on close if I created a new file via ctrl+N (even though a filename/location for it was never specified). Instead it stores it somewhere and is right there when I open it next time.
If it prompts it should be in such a way that can't result in the loss of opened files.

### Actual Behavior
Session data disappeared. Apparently because of the interrupted closing process.

### Debug Information

In the meanwhile I upgraded NPP so I don't have debug info. Though it was not a very old version probably 7.8 x64. (That's the last I had locally.)

**Comment by ArkadiuszMichalski** [comment]
Not fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7839 in [7.9.3](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Changes#793) version? @mzso 7.8 probably was to old.

**Comment by sasumner** [comment]
Seemingly very current and relevant to this issue:  https://community.notepad-plus-plus.org/post/64993

**Comment by ArkadiuszMichalski** [comment]
https://community.notepad-plus-plus.org/topic/21046/files-corrupted-in-recent-update << another report with corrupted files.

**Comment by Exrace** [comment]
Same as my issue.
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9850
Moderator should combine these issues as many are reporting the same thing on forced OS shutdowns.

**Comment by mzso** [comment]
Still happening here. It's definitely glitch. Last time I saw notepad closing its own tabs then halting shutdown* because of a prompt.
Either it was the "modified by another program" or "doesn't exist, do you want to keep" prompt, so largely irrelevant stuff.
What happened then is that notepad just overwrote the proper session with nothing or that single text file in the session.

*Since it became obvious what is going to happen I could save a backup of the session file.

**Comment by Oceanboy1330** [comment]
Sorry to Bump this Topic, but Same Here.

**Comment by donho** [comment]
Fix by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6000f3bb21a42a4d28d068617e0dc642ef739b26
