### ISSUE TITLE
Copy command for Search Results should be unavailable when no text is selected

### ISSUE THREAD

**Issue by GhbSmwc** [notepad-plus-plus/notepad-plus-plus#9757]
When using the `find` function and use “Find all in Current Document”, rightclicking on the green text representing the file path and selecting “Copy” on the context menu does not update the clipboard.
![FindAllInCurrentDocument](https://user-images.githubusercontent.com/13095760/114314777-187f4f80-9aca-11eb-869b-f701d247c8ab.gif)

**Comment by sasumner** [comment]
The _Copy_ command you show in your screencast is the one that copies selected text in the _Search results_ window.  As you don't select any text there before you initiate the copy, there is nothing to copy.

Probably _Copy_ should be greyed out, i.e., disabled in such a circumstance.  I will use this issue to make that change to the software.

**Comment by GhbSmwc** [comment]
I found out that selecting “Copy Selected Line(s)” on the context menu works. Before the update, “Copy” would copy all the text in the results only (not the page numbers, the file path in green, and the search status in blue).

**Comment by sasumner** [comment]
Yes, there used to be only one copy on the right-click context menu.  Now there are two.  The user manual has been updated to describe how each works and their differences.

IMO, "Copy Selected Lines(s)" does not do a good job of describing the functionality, but that text is what the author of Notepad++ wanted.

**Comment by sasumner** [comment]
I took some "liberty" and changed the title of the issue (to something that can be fixed).

**Comment by donho** [comment]
@sasumner 
> IMO, "Copy Selected Lines(s)" does not do a good job of describing the functionality, but that text is what the author of Notepad++ wanted.

Sorry, I don't recall your suggestion. Could you remind me it please?

**Comment by sasumner** [comment]
>Sorry, I don't recall your suggestion. Could you remind me it please?

I don't recall it exactly, and it probably isn't worth trying to find it.
It is difficult to find good text for this menu item, meaning keeping it reasonably short.

Some possibilities:

* `Copy Special` (and define it in the user manual)
* `Copy original lines in tree of caret/selection` (not entirely true for long lines that might end with `...`)
* `Copy lines touched by selection without search data` (does not convey the tree-like nature of what is copied)

The second and third examples above are relatively long and are still not totally explaining the functionality.

**Comment by sasumner** [comment]
@donho Does the upvote mean you are considering to change `Copy Selected Line(s)` to something else?

**Comment by sasumner** [comment]
@donho Note that although this PR changes only `Copy` to be disabled if there is no selected text. other entries in the context menu of _Search results_ could/should be disabled if conditions are not correct for running them.  

I looked at doing that but there is a bit of work to it, so I just wanted to do `Copy` with this current issue/PR -- because I think this is the type of command that users definitely want/need to see disabled if there is nothing to copy (and it was what misled the OP of the issue to pick the wrong command).

I will create another issue to deal with proper disabling of the remaining items on this context menu.

**Comment by donho** [comment]
> Does the upvote mean you are considering to change Copy Selected Line(s) to something else?

I was considering about renaming "Copy". But when I compare it with Copy command of main menu & context menu, both commands have the same behaviour. The difference was the Copy in the search result is still available while no selected text is present. So let's keep the name as it is.

> Note that although this PR changes only Copy to be disabled if there is no selected text. other entries in the context menu of Search results could/should be disabled if conditions are not correct for running them.

"Copy" is the most confused case (with "Copy selected line(s)") while no text selected. You can work on it to disable the other commands in some contexts but I doubt if it's worth (The PR will be accepted if the coding effort is minimal for such "feature").

**Comment by sasumner** [comment]
>I was considering about renaming "Copy"

"Copy" is rather a standard for what _Copy_ does here, so I think that is what it should remain.

>but I doubt if it's worth...

Okay, then, I'll not create an issue about it then.
