### ISSUE TITLE
line numbering

### ISSUE THREAD

**Issue by HaPe4** [notepad-plus-plus/notepad-plus-plus#9758]
### Description of the Issue

Since version 7.9.2 i am not able to turn off line numbering; the option **Display line number** does´nt exist anymore.

### Steps to Reproduce the Issue

1. OpenSettings -> Preferences
2. Editing see under option-group Line Wrap
3. No CheckBox **Display line number** in 7.9.2-...

### Expected Behavior

CheckBox **Display line number** is available

### Actual Behavior

3. No CheckBox **Display line number** in 7.9.2-...

![Linenumbering](https://user-images.githubusercontent.com/29651009/114367745-0b6f6880-9b7d-11eb-865c-1d918d22e96f.jpg)

**Comment by dail8859** [comment]
It was moved under 'Margins/Border/Edge'

![image](https://user-images.githubusercontent.com/3694843/114388979-6778c380-9b62-11eb-91ee-7399550dfbc4.png)

**Comment by sasumner** [comment]
Strange that people don't "look around" in the Preferences for things, before going to the trouble of opening an issue.

**Comment by HaPe4** [comment]
Maybe strange for You.
When searching in google, the old place is shown.
In Notepad++ history i found infos about 7.9.1, 7.9.3, 7.9.4, ... at usual place but not for 7.9.2. For 7.9.2 the history is on another place. Nevertheless, in 7.9.2 history i found no info about line-numbers.
Ok, i missend a extended search in the options dialog.

Please excuse my fault.

**Comment by sasumner** [comment]
>When searching in google, the old place is shown.

When your map says something different from the road ahead...believe the road, not the map.

**Comment by HaPe4** [comment]
I used the road (Notepad++ history), but the road didn't tell me which branch to take.

**Comment by sasumner** [comment]
The Notepad++ history is more like the map.  The real road in this case is the Notepad++ Preferences screens, and of course the N++ user manual; see https://npp-user-manual.org/docs/preferences/ 

Don't feel bad about yourself for not "looking around" in the Prefs -- it tends to happen -- something gets moved in the Preferences and people can't get their head around it being different than it used to be.  As more settings are added, these screens get a bit tight on space, so new ones are made and things are reorganized.
