### ISSUE TITLE
its very great having one option in preferences & searching that notepad++ does not remember the searched items.

### ISSUE THREAD

**Issue by zahra21** [notepad-plus-plus/notepad-plus-plus#9759]
hello.
when openning file dialog in a document and searching some words or phrases, notepad++ remembers the words or phrases which we searched.
i could find these items in my notepad++ searched words and phrases in config.xml file in appdata.
i believe that the best place for this option is preferences and searching.

**Comment by sasumner** [comment]
This is not an "issue".
Actually, I'm not sure what this is.
If you are indeed working towards making an issue, please use the "issue template" instead of deleting it out while composing.

**Comment by zahra21** [comment]
i dont know whats the reason that i cant reply you directly and should send my attitude in seperate comment rather than replying to your previous comment.
i dont know why you closed my report.
i did not say and did not ment its an issue i mean that its a great inhancement or benefit for notepad++ users that notepad++ does not save and not remember previous searched items.

**Comment by zahra21** [comment]
> 
> 
> This is not an "issue".
> Actually, I'm not sure what this is.
> If you are indeed working towards making an issue, please use the "issue template" instead of deleting it out while composing.

i dont know why you closed my report.
i did not say and did not ment its an issue i mean that its a great inhancement or benefit for notepad++ users that notepad++ does not save and not remember previous searched items.

**Comment by sasumner** [comment]
Okay, so then this is a Feature Request to have a means to NOT remember previous search data in the Find family of dialog windows, for the dropdown components (e.g. _Find what_, _Replace with_, _Directory_, etc)?  Is that correct?

IF it is correct, then:

What is the use-case for this?
In other words, what is the great benefit for NOT having this information available for later recall/reuse.

Suggestion:  If English is not your native language, perhaps use a translator (such as deepl) to write in your language of comfort and translate into English before posting here.

**Comment by zahra21** [comment]
> 
> 
> Okay, so then this is a Feature Request to have a means to NOT remember previous search data in the Find family of dialog windows, for the dropdown components (e.g. _Find what_, _Replace with_, _Directory_, etc)? Is that correct?
> 
exactly its correct, i am very glad and thanks God that my english is understandable for at least native english speakers!
> IF it is correct, then:
> 
> What is the use-case for this?
> In other words, what is the great benefit for NOT having this information available for later recall/reuse.

i did not find any program that remembered searched items, i really dont like its current behaviour.
all of my text files are in the field of technology and religion.
i ment, that all of my files are about technology and religion.
for example: i open a file about computer and use find dialog, and searche for some phrases and sentences.
then, i close notepad+
and after a month later, i can find the items which i typed in the last month even my current document is about religion which have not the same words!
its a helpful feature or an inhancement.
they are tens of menus that are available in notepad++ that i dont use them and even i dont know what are they! and whats the reasons that they are present in notepad++ preferences and menus.
but programmers and professional users of notepad++ requested current features which are useless for me or at least unknown for me.
> 
> Suggestion: If English is not your native language, perhaps use a translator (such as deepl) to write in your language of comfort and translate into English before posting here.

i contact you from Iran, english is not certainly my native language.
but most softwares dont support farsi (persian) very well.
the only working software is google translation that at least did not work for me perfectly with religious text many times.

**Comment by zahra21** [comment]
0 please re-open this issue and let other users and developers mention their views about my requested feature.
they are hundreds of issues or reports which are not accepted by developers at first, but those issue remain open and some other users vote for them and are agree with them and finally developers accept and implement them!

**Comment by mere-human** [comment]
@zahra21 Have you tried deletion the search result one by one as specified in the documentation?

> Unwanted items in the histories may be removed by dropping-down the box, highlighting the item to be removed, and pressing the Delete key (requires version 7.9.3 or later).

Here is the full page:
https://npp-user-manual.org/docs/searching/

**Comment by zahra21** [comment]
> 
> 
> @zahra21 Have you tried deletion the search result one by one as specified in the documentation?
> 
> > Unwanted items in the histories may be removed by dropping-down the box, highlighting the item to be removed, and pressing the Delete key (requires version 7.9.3 or later).
> 
> Here is the full page:
> https://npp-user-manual.org/docs/searching/

no, i did not.
as you mentioned, it requires version 7.9.3
but my favorite version is 7.9.1
i love a version which works in all operating systems
and, 7.9.1 has everythings which i expect to have.
