### ISSUE TITLE
Explorer favorite in C:\Program Files\Dir being changed use Program Files (x86)

### ISSUE THREAD

**Issue by cricciuto** [notepad-plus-plus/notepad-plus-plus#976]
Windows 7 64-bit
In Explorer I have a "Favorites" bookmark set to:
"C:\Program Files\Directory1\Directory2"
but in the open dialogue in Notepad++ clicking on the bookmark tries to go to:
"C:\Program Files (x86)\Directory1\Directory2"

In File Explorer I can get to "C:\Program Files\Directory1\Directory2" just fine when clicking on the bookmark.

**Comment by linquize** [comment]
because the official npp binary is a 32-bit program

**Comment by cricciuto** [comment]
Ohhh, that makes sense. I didn't even think about that.
