### ISSUE TITLE
Empty panels

### ISSUE THREAD

**Issue by IvanKucherov** [notepad-plus-plus/notepad-plus-plus#9760]
![image](https://user-images.githubusercontent.com/48240790/114395759-6c129b80-9ba5-11eb-8ff4-201e567f454a.png)

**Comment by donho** [comment]
Please provide us more information instead of post a screenshot - that won't help us to solve your problem.
Please follow the instructions of issue template while you open a new issue. Thank you.

**Comment by sasumner** [comment]
This has come up a few times in the Community since the release of 7.9.5.
For example, here's one:  https://community.notepad-plus-plus.org/topic/20997

A reboot seems to cure it, but obviously that isn't a great fix to the problem.

**Comment by sasumner** [comment]
Another Community posting: https://community.notepad-plus-plus.org/topic/21024

**Comment by pryrt** [comment]
Also, https://community.notepad-plus-plus.org/topic/20996/tabs-are-floating-after-upgrade-to-7-9-5 provided the Debug Info of that system, and was helpful explaining a procedure (ending in reboot) that stopped the problem.

**Comment by pryrt** [comment]
another new report, where the problem comes back after having looked okay: https://community.notepad-plus-plus.org/topic/21053/layout-breaks-after-a-few-days

**Comment by pryrt** [comment]
@IvanKucherov ,  

Do you still have the problem?  If so, do you use nVidia video card / GPU?  You might want to try to update video drivers and then reboot.

Forum users [Dan Schreck 13 days ago](https://community.notepad-plus-plus.org/post/64735) and [DomWesker just today](https://community.notepad-plus-plus.org/post/65188) both use nVidia GPU and both have reported that updating the video drivers and rebooting has fixed the problem -- and Dan's was almost 2 weeks ago, so I would hope that if he'd had the problem return, he would have come back and told us.

**Comment by IvanKucherov** [comment]
No, it's gone after reboot.
Yes, I do have nVidia GPU.
