### ISSUE TITLE
"Save As" with multiple "new" tabs attempts to "Save All"

### ISSUE THREAD

**Issue by endigrow** [notepad-plus-plus/notepad-plus-plus#9761]
### Description of the Issue
Select "File-->Save As" for "new 4" opens a dialog trying save "new 2" NOT "new 4". It then proceeds to attempt to do the same for "new 3" as well before attempting save "new 4"

### Steps to Reproduce the Issue

1. Multiple tabs are open: "new 2", "new 3" and, some named. 
2. "New" icon creates "new 4". 
3. Change language to SQL for "new 4". 
4. Paste code into "new 4". 
5. Select "File-->Save As". 
6. This opens a dialog trying to save "new 2" NOT "new 4". It then proceeds to attempt to do the same for "new 3" as well before attempting save "new 4"

### Expected Behavior
"File-->Save As" should only attempt to save the CURRENT file associated with the tab that has the focus and only open ONE dialog.

### Actual Behavior
opens a dialog trying save "new 2" NOT "new 4". It then proceeds to attempt to do the same for "new 3" as well before attempting save "new 4"

### Debug Information
Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.867
Current ANSI codepage : 1252
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll SQLinFormNpp.dll 

Searched for the topic in the Community and in Known issues and did not see this.

**Comment by sasumner** [comment]
Cannot reproduce.
At step 6, for me the file prompted to saveAs is `new 4`, not `new 2`.
In other words, I get the "Expected behavior" described above.
So my conclusion, barring further information being supplied is that there is no problem.
