### ISSUE TITLE
Search string is not recognized

### ISSUE THREAD

**Issue by Gaean1** [notepad-plus-plus/notepad-plus-plus#9763]
### Description of the Issue
I downloaded a text log file, unzipped it and opened in Notepad++  V.7.9.1
It was a sip log so I searched on my test phone number which it could not find. When I scrolled to the bottom of the file there it was. For some reason the search string doesn't match the log string.

### Steps to Reproduce the Issue

1.  Closed Notepad ++ and then reopened the unzipped file. Still can't find the string.
2. Searched forward and backwards, it never finds the matching string.
3. 

### Expected Behavior
It should take me to the first occurrence of the string.

### Actual Behavior
It says it can't find the text.

### Debug Information

Notepad++ v7.9.1   (64-bit)
Build time : Nov  2 2020 - 01:07:46
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.906
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

![image](https://user-images.githubusercontent.com/82412571/114453102-0c5cc600-9b8e-11eb-8a5b-7a471b253259.png)

**Comment by sasumner** [comment]
Untick _Match whole word only_
