### ISSUE TITLE
Change name of programming language from Nimrod to Nim

### ISSUE THREAD

**Issue by trustable-code** [notepad-plus-plus/notepad-plus-plus#9768]
The programming language ``Nimrod`` was renamed to ``Nim`` in 2014.
Notepad++ still shows it as ``Nimrod`` at different places in the UI, see screenshots in https://github.com/notepad-plus-plus/npp-usermanual/pull/195#issuecomment-819451573.
The file extension ``.nim`` did not changed.

**Comment by sasumner** [comment]
>The programming language Nimrod was renamed to Nim in 2014.

Here's a reference for the name change: https://forum.nim-lang.org/t/2994
There appear to be many others.

The screenshots in the OP's link were not meant to be an exhaustive enumeration of ALL of the places `Nimrod` appears in the UI, just some examples.
