### ISSUE TITLE
The results in "Find in Files" does not display the full result in "Search results" if it contains a new line, and there is nothing to make it show the full result in the "Search results" window

### ISSUE THREAD

**Issue by karl-police** [notepad-plus-plus/notepad-plus-plus#9771]
### Information
Notepad++ v7.9.5 (32-bit)

### Description
The results in "Find in Files" does not display the full result in "Search results" if it contains a new line, and there is nothing to make it show the full result in the "Search results" window. "Word wrap long lines", doesn't seem to be doing anything either for this case.

### Steps to Reproduce the Issue
1. Create a file, name it whatever. Use "Windows (CLRF)", otherwise change RegEx Expression.
2. Put this text inside the file. And save it.
```
TEST
{
This is a text.
}

This is another text.
```
3. Go to Notepad++ and press `CTRL+F` and go to the "Find in Files" tab.
4. Set the directory to wherever the test file is. At "Search mode", turn on "Regular expression" and ensure the box next to it is unchecked.
5. Put this `TEST\r\n{\r\n.*\r\n}` in the "Find what" field. Then press "Find All".

&nbsp;
After that you should get this in your "Search results" window.
![](https://i.imgur.com/WmqsQHb.png)

&nbsp;
When you double click the result, it will open the result and select the found result in the file.
![](https://i.imgur.com/IQm52EQ.png)

Here you see that it selected all that matched the expression.
However, in the "Search results" it only shows one line and the rest breaks.

I wanted there to be a way to make it show all the results in "Search results" directly.

**Comment by sasumner** [comment]
>However, in the "Search results" it only shows one line

Yes, this is how it works.  
It is a "by design" behavior.

If you are interested in seeing data that is not on the first line of your match, you can change your search to, for example: `TEST\r\n{\r\n\K.*\r\n}` which for your sample text would then show:

![image](https://user-images.githubusercontent.com/30118311/114890715-453cab00-9dd9-11eb-9975-cfc7af156aba.png)

Also, the _Mark_ command (Ctrl+m to initiate) may be something helpful to you.

**Comment by karl-police** [comment]
> > However, in the "Search results" it only shows one line
> 
> Yes, this is how it works.
> It is a "by design" behavior.
> 
> If you are interested in seeing data that is not on the first line of your match in the _Search results_ area, you can change your search to, for example: `TEST\r\n{\r\n\K.*\r\n}` which for your sample text would then show:
> 
> ![image](https://user-images.githubusercontent.com/30118311/114890715-453cab00-9dd9-11eb-9975-cfc7af156aba.png)
> 
> Also, the _Mark_ command (Ctrl+m to initiate) may be something helpful to you.

What's `\K` for?
And what if there's a new line inside the brackets?

**Comment by sasumner** [comment]
>What's \K for?

`\K` means forget about the match to its left.
The match has to be there, but forget about it.
What this does for your example, is to bring a different part of your match into view for you in the _Search results_ window.

>And what if there's a new line inside the brackets?

I don't understand this question.

**Comment by karl-police** [comment]
> > What's \K for?
> 
> `\K` means forget about the match to its left.
> The match has to be there, but forget about it.
> What this does for your example, is to bring a different part of your match into view for you in the _Search results_ window.
> 
> > And what if there's a new line inside the brackets?
> 
> I don't understand this question.

Let's say it would be like this.

```
TEST
{
This is a text.
Another text.
}

This is another text.
```

**Comment by sasumner** [comment]
It all depends upon what single-line of that you'd want to see in the _Search results_ window.

**Comment by karl-police** [comment]
What about multi-line?

**Comment by sasumner** [comment]
Earlier I said:

>Yes, this is how it works.
It is a "by design" behavior.

Probably what I should have added is:  "It isn't going to be changed to support multiline, sorry".

**Comment by karl-police** [comment]
Wait, what design?

**Comment by sasumner** [comment]
"by design" means that it was designed by Notepad++ creators to be the way it is, because they wanted it to be that way.

**Comment by karl-police** [comment]
> "by design" means that it was designed by Notepad++ creators to be the way it is, because they wanted it to be that way.

Do they want to keep that part, that way?

**Comment by sasumner** [comment]
>Do they want to keep that part, that way?

Yes.

I feel like I'm being trolled, so in that event, this is my last posting to this issue.

**Comment by karl-police** [comment]
> > Do they want to keep that part, that way?
> 
> Yes.
> 
> I feel like I'm being trolled, so in that event, this is my last posting to this issue.

Unsure, actually I am the one that feels like is being trolled.
Soo...

I think maybe we missunderstood both something?

I don't understand, why they would not support results that show on multiple lines

or an something like a `\K` for it.
