### ISSUE TITLE
Ctrl-Tab context menu with file names in dark mode needs to be dark!

### ISSUE THREAD

**Issue by liudr** [notepad-plus-plus/notepad-plus-plus#9774]
To protect my eyes, I use dark theme on everything, including NPP. I usually have 30-40 files open, on split window, with multi-line tabs so I can easily view files in my project. I notice that the list of files when I ctrl-tab is displayed in very bright yellow background. So I had to close my eyes when doing ctrl-tab and I can feel the light through my eyelids. Plus I can’t see which file I’m tabbing into so it’s counter-productive. I wonder if you could make some change to display a dark-themed file list when ctrl-tabbing. It would be great.

**Comment by ozone10** [comment]
Implemented with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bf6cb36d4888ec241bde7be8f425326c4cb1c4c3, can be closed
