### ISSUE TITLE
Feature request: option to add prefix and suffix to lines

### ISSUE THREAD

**Issue by FrostShock** [notepad-plus-plus/notepad-plus-plus#9779]
Notepad2 has a wonderful option to add prefix and suffix to lines (Alt+M   -   Edit - Block - Modify Lines...)

Please add this feature, many times I have do quickly add a prefix to a block of lines and to append something to a block of lines, and I am 100% sure that many other users and coders need to do that.

Thank you

**Comment by sasumner** [comment]
In Notepad++ this can easily be accomplished by regular expression search mode replace-all operations, with _Wrap around_ option ticked.

------------------------------------------

To prefix lines:

search: `^`
replace: whatever-you-want-the-prefix-to-be

To suffix lines:

search: `$`
replace: whatever-you-want-the-suffix-to-be

------------------------------------------

Be sure to specify "Regular expression" for the "Search mode", like this:

![image](https://user-images.githubusercontent.com/30118311/115162619-9adfb480-a072-11eb-99e1-201c8f47e7a3.png)

**Comment by FrostShock** [comment]
The fact that there is a solution is really great indeed.

Yet this solution is way more complicated and time consuming than pushing a hotkey that opens a small window asking for prefix and the text to append to each of the selected lines.

In Notepad2 you do this by pushing Alt+M.

I think that adding such feature in Notepad++ would be a great feature.

**Comment by sasumner** [comment]
There is also the possibility to "script" a solution.
See [HERE](https://community.notepad-plus-plus.org/topic/16337/feature-request-modify-lines-dialog-for-adding-prefix-suffix-to-lines) for such an approach.
Enjoy.
