### ISSUE TITLE
Save don't work correctly

### ISSUE THREAD

**Issue by nicolas2k** [notepad-plus-plus/notepad-plus-plus#978]
Hi,

Since a several before version of npp (and 6.8.3), Sometime, the function (Save or ^S) don't work correctly but it's not saved !
I cannot find a cause of malfunction in local disk and it's very mysterious.

Nicolas

**Comment by donho** [comment]
I cannot reproduce it.
Could you provide the instrictions to reproduce it?

**Comment by nicolas2k** [comment]
I cannot reproduce it systematic too , but only some time during 2 years !

I just noticed that the tab is grayed out (not red).

Of course, we have a different version of code under sheel-dos with "type
toto.pl" command

Nicolas


2015-09-30 16:30 GMT+02:00 Don HO <notifications@github.com>:

**Comment by donho** [comment]
The gray disk icon means the file is read only.
So it's normal that you cannot save.

**Comment by nicolas2k** [comment]
This ticket is closed !
arrf, if you want that it's not grey but blue !



2015-09-30 18:29 GMT+02:00 Don HO <notifications@github.com>:

**Comment by nicolas2k** [comment]
one solution to resolve is close this file 'toto.pl' and reopen !

2015-09-30 18:36 GMT+02:00 Nicolas Kerspern <nicolas.kerspern@gmail.com>:

**Comment by donho** [comment]
I can reopen the ticket if the bug can be reproductible - that means you reproduce it steadily and the detailed instructions to reproduce it are provided. Otherwise I can do nothing about it.

**Comment by nicolas2k** [comment]
Other remark, if this tab is grey, we cannot modify this code but it did
not to do !

2015-09-30 20:19 GMT+02:00 Don HO <notifications@github.com>:
