### ISSUE TITLE
Feature request - hotkey to remove first character from all the selected lines

### ISSUE THREAD

**Issue by FrostShock** [notepad-plus-plus/notepad-plus-plus#9780]
Deleting the first character from all the selected lines is something used frequently, and I think there should be such an option and also a hotkey for that

Please implement this feature,
Thanks in advance

**Comment by sasumner** [comment]
Why do you think this is a frequently done thing?  
While it has occasional use, I don't think it is needed that often.

It can be done in Notepad++ in at least 2 easy ways.

-------------------------------------

Way 1:

![image](https://user-images.githubusercontent.com/30118311/115162736-1e010a80-a073-11eb-90bc-5f6d40f19ae9.png)

A bit cryptic to remember, but you can make a macro for it and bind it to a hotkey, to achieve exactly your desire.

If you want it only from selected lines, additionally tick the _In Selection_ checkbox.

-------------------------------------

Way 2:

Make a column selection of the first column, over as many lines as you desire.
A column selection is made by either using Shift+Alt+arrow keys, or by holding Alt down while selecting text with the mouse.
After the desired column 1 data is selected, press the delete key.

-------------------------------------

You can't make a hotkey macro out of "Way 2" so probably "Way 1" is better for your case.

**Comment by FrostShock** [comment]
Thank you very much for your answer.

I am not a programmer but I am using sed, awk, grep and other gnuwin32 tools on Windows, quite frequently. Processing various text files with these utilities, I find myself many times making use of Notepad2 and I am using many times Alt+Z to delete the first character of the selected lines. A few lines can be indented more than necessary and I quickly fix that with a hotkey.

I find the column selection really great, yet, when you want to strip the first character for only 2 or 3 lines, a hotkey is quite faster than selecting columns (by using keyboard or keyboard + mouse)

It is impossible for me to believe that I'm the only one who uses this thing quite often, since I am using common tools and doing  usual stuff like preparing a Wikipedia page or downloading a web page and searching for something inside it.

**Comment by sasumner** [comment]
It sounds as if what I described as "Way 1" is the way you should proceed (with the making of a macro out of it).
