### ISSUE TITLE
Erratic NumPad behaviour

### ISSUE THREAD

**Issue by Haftmann** [notepad-plus-plus/notepad-plus-plus#9785]
### Description of the Issue
On entering Alt+Num147 for entering typographic quote character, cursor jumps to left, then character is inserted.
Applies when NumLock is not active: Alt+Num4 acts as Alt+Left.
Old error, present since >10 years.

### Steps to Reproduce the Issue
* Switch off NumLock
* Hold ALT key
* Enter 0-1-4-7 on numeric keypad
* Release ALT key

### Expected Behavior
“ inserted at cursor position

### Actual Behavior
“ inserted at line start and cursor moved.
Notice: For Alt+Num0148, cursor jumps to end of line.

### Debug Information
Notepad++ v6.8.8
Build time : Dec 10 2015 - 01:11:37
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : NppExec.dll

**Comment by sasumner** [comment]
Can't reproduce in Notepad++ 7.9.5.
Worked fine to insert the characters without moving the caret after:

![image](https://user-images.githubusercontent.com/30118311/115399169-ea7ac900-a1b5-11eb-929f-10d3afe9173e.png)

**Comment by sasumner** [comment]
Note: I did try it in 6.8.8 and it does have the bugs described by @Haftmann
