### ISSUE TITLE
Suggestion: Close All Windows option

### ISSUE THREAD

**Issue by JamesB7** [notepad-plus-plus/notepad-plus-plus#9788]
Would you please add a Close All Windows option to the Windows menu? Right now, if I want to start afresh, I need to go to Window, Windows, select them all, and click Close. I do this a few times a day. Would be nice if it just had a menu option. (Visual Studio has this.)

**Comment by sasumner** [comment]
>Would be nice if it just had a menu option

It does:

![image](https://user-images.githubusercontent.com/30118311/115891553-3337b980-a424-11eb-80f6-b494026e5d95.png)
