### ISSUE TITLE
[Feature request]: EOL to space, but ignore double EOLs

### ISSUE THREAD

**Issue by pigsonthewing** [notepad-plus-plus/notepad-plus-plus#9799]
I regularly use "EOL to space", under the "Edit"/"Bank Operations" menu, but have to then manually re-apply double EOLS, for paragraphs. For example, in text like:

> Lorem ipsum dolor 
> sit amet, consectetur adipiscing 
> elit, sed do eiusmod tempor 
> incididunt ut labore et dolore 
> magna aliqua. 
>
> Ut enim ad minim veniam, quis 
> nostrud exercitation ullamco 
>laboris nisi ut aliquip ex ea 
> commodo consequat.

whee I want the result to be:

> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
> 
> Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

Please can the menu have an "EOL to space (maintain paragraphs)" option, to do this?

**Comment by sasumner** [comment]
This _Replace All_ operation seems to do it.  You can make a macro out of it for your needs.

![image](https://user-images.githubusercontent.com/30118311/115991240-a44aae80-a595-11eb-990f-2a155b5e079a.png)

find: `(\R{2,})|\R`
replace: `(?1${1}: )`
