### ISSUE TITLE
default FunctionList sorting

### ISSUE THREAD

**Issue by freggeldoe** [notepad-plus-plus/notepad-plus-plus#98]
I always sort functions by name and have to change the sort order every time I reopen notepad++ for each of my opened files. Please keep the last sort-order as a default for newly opened files as well as open files when reopening notepad++ or provide a setting to define the default sort order.

**Comment by Chrissstrahl** [comment]
I also like this idea, because I have the same problem :)

**Comment by amiga-500** [comment]
And its still a problem after 2 years.

**Comment by jmihalko** [comment]
I agree, this is a real pain.  I think just a setting to define the default sort order would be sufficient and hopefully quicker to implement so maybe we can still get the feature.....before I retire :)

**Comment by elmonty** [comment]
If NP++ would simply remember the last sort order, that would be great!

**Comment by donho** [comment]
Function list sorting has been implemented since long time ago.

**Comment by MetaChuh** [comment]
@donho
verified label because:

the default setting is unsorted.
author wanted the alphabetical sort setting to be saved and remembered.
alternative he suggested to make alphabetical sort as default.

**Comment by freggeldoe** [comment]
@donho: Please reconsider your close-decision. I was asking for a way to keep alphabetical functionList-sorting either by changed default or by a setting.
