### ISSUE TITLE
Linearize XML 

### ISSUE THREAD

**Issue by jjeffman** [notepad-plus-plus/notepad-plus-plus#980]
Sometimes we may want to linearize an XML and go back to the indented form to continue to build it in a friendly way. Why when we clicked on the menu option "XML Tools"->"Linearize XML" the option is not checked and unchecking it could return to the indented form ?

Best Regards.

Jayme

**Comment by dail8859** [comment]
This should be reported over at the [Sourceforge project page](http://sourceforge.net/p/npp-plugins/_list/tickets?source=navbar) for XML Tools since this is not a standard plugin for Notepad++. Thanks.

**Comment by dail8859** [comment]
3rd party plugin related.
