### ISSUE TITLE
Mark All "Match whole word only" settings not working

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#9803]
### Description of the Issue
Set only "Match whole word only" for Mark All, then do some "Mark All" operations, the result is unexpected. 

### Steps to Reproduce the Issue

1. Set only "Match whole word only" for Mark All
2. Select "train" of "training" of the the 1st line of following text, then apply Mark all action (Menu "Mark All -> Using 1st style") 
```
training
train
trainspotting
train
```

### Expected Behavior
Only the words "train" of the 2nd & 4th line are highlighted.

### Actual Behavior
All the (4) occurrences "train" are highlighted.

### Debug Information
Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.928
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll NppXmlTreeviewPlugin.dll XMLTools.dll

**Comment by sasumner** [comment]
@donho

So the original code (before #9796) reads like this:

```
// if whole word is selected for being colorized, isWholeWord option in Find/Replace dialog will be checked
// otherwise this option is false, because user may want to find the words contain the parts to search 
opt._isWholeWord = isWholeWordSelected?_options._isWholeWord:false;
```

The comment is correct with what the code is doing (saying this because sometimes comments don't match reality).

I'm stating this because it appears that the behavior (pre- and post-9796) was very intentional by whomever wrote the code.

So I just want to confirm that we definitely want to change the behavior, and if we've considered that changing the behavior might upset some users...

Note: 9796 changed the behavior in one way -- how the options are specified -- but it didn't change core behavior of how the feature works.  This issue would.

**Comment by donho** [comment]
@sasumner 
I did a blame, and it was me...
What do you think about the correct behaviour about Mark All with "Match whole word only" is checked?

**Comment by sasumner** [comment]
I'm not sure about what is "correct behavior".
As a user, I'm sort of used to it the way it is now, but I'm just one user.

**Comment by dinkumoil** [comment]
Features/options should work like they are described. If option "Match whole word only" is checked and I get search results where the searched term is only a part of, I think at least "Uhm, that's strange, it's not what I told this software to do. This smells like a bug".

IMO it should not make a difference if I select a whole word or only a **part** of a word to search for, in both cases I expect the same search results.

**Comment by donho** [comment]
@dinkumoil is right. And it's how it works the Mark in Find/Replace dialog.
So @sasumner could you do a PR to fix the current behavour please (by removing the comment)?

**Comment by sasumner** [comment]
Sure, I'd better change the code as well, in addition to moving the comment. :-)

It seems like maybe we are missing something, as to why it was done that way in the first place, though.
It appears very intentional.

**Comment by donho** [comment]
Thank you.
It could be a "feature" asked by a (some) user(s), so the behaviour has been changed.
