### ISSUE TITLE
Issue with Unicode fonts around matching braces

### ISSUE THREAD

**Issue by JPeroutek** [notepad-plus-plus/notepad-plus-plus#9805]
### Description of the Issue

When mouse cursor is near a matched brace `(){}`, it causes unicode characters contained in the braces to be rendered as squares ⎕

### Steps to Reproduce the Issue

Example program (written in APL)
``` 
polyval ← {+/⍵×⌽⍺*(⍳≢⍵)-1}

```

### Expected Behavior
![image](https://user-images.githubusercontent.com/1711673/116145125-8159f080-a6a2-11eb-8ae7-a0db0a9579d8.png)

### Actual Behavior
When the cursor is anywhere on the line adjacent to a matchable brace, many of the characters turn into boxes.  In this example, the cursor is at the end of the line.
![image](https://user-images.githubusercontent.com/1711673/116145148-89b22b80-a6a2-11eb-8dc1-c8134408a5ff.png)

### Debug Information
Notepad++ v7.9.1   (32-bit)
Build time : Nov  2 2020 - 01:03:56
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19042.928
Current ANSI codepage : 1252
Plugins : CsvQuery.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll

**Comment by JPeroutek** [comment]
Weirdly enough, a similar one-liner does not exhibit this behavior at all:
```
polyval ← {0=≢⍵:0⋄(¯1↑⍵)+⍺×(⍺∇¯1↓⍵)}

```
![image](https://user-images.githubusercontent.com/1711673/116145525-0e9d4500-a6a3-11eb-9477-9701313a0521.png)

**Comment by sasumner** [comment]
Can you check this setting and tick the box to turn it on if it is off?:

![image](https://user-images.githubusercontent.com/30118311/116150016-d270e100-a6b0-11eb-9351-e6a342c397b0.png)

**Comment by JPeroutek** [comment]
> 
> 
> Can you check this setting and tick the box to turn it on if it is off?:
> 
> ![image](https://user-images.githubusercontent.com/30118311/116150016-d270e100-a6b0-11eb-9351-e6a342c397b0.png)

That seems to have done the trick!  If you'd like, you can answer the question [here](https://superuser.com/questions/1644703/why-does-notepad-display-some-unicode-characters-as-only-if-the-mouse-curs) as well, and I'll accept your answer.  If not, I'll post it later tomorrow so the community can find it.

**Comment by sasumner** [comment]
@donho 

There have been many questions opened as issues that end when I post a "DirectWrite" answer.
When does it become time to release Notepad++ with "DirectWrite" ticked by default?

**Comment by donho** [comment]
@sasumner 
I'm not so sure.
I do remember there's the performance issue when "DirectWrite" is ON. That's why it's not set ON as default.

**Comment by sasumner** [comment]
Ah, OK.  So we keep answering these questions. :-)

**Comment by donho** [comment]
@a-polivanchuk 
Can we create a FAQ section in wiki for such purpose?
So we just provide the like to reply people who got the same problem.

**Comment by donho** [comment]
@ArkadiuszMichalski 
Can we create a FAQ section in wiki for such purpose?
So we just provide the like to reply people who got the same problem.

**Comment by ArkadiuszMichalski** [comment]
Yes, FAQ focusing for common bugs would be useful. I'll take care of it, but my English is what it is, so someone has to correct it after all:)

**Comment by ValZapod** [comment]
This is my issue. https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8305

**Comment by ValZapod** [comment]
> contained in the braces to be rendered as squares ⎕

NO. Contained on that line and only SOME characters.
