### ISSUE TITLE
Function list not reading function names beginning with reserved words for php

### ISSUE THREAD

**Issue by alokg1019** [notepad-plus-plus/notepad-plus-plus#981]
If a function is named beginning with a reserved word in php , then the function list window is not able to search that function if searched for using the whole name or beginning letters.
eg: in php if we name a function like so:

function forgotPassword()
{
   // some code
}

Then the above function name cannot be searched for beginning with "f" since it contains a reserved  
word "for" of php language
![screenshot 2015-10-02 03 34 36](https://cloud.githubusercontent.com/assets/6104480/10235126/4a4f8d5e-68b7-11e5-978a-5d15e36412d3.png)

**Comment by linquize** [comment]
Update delayed? Was it `orget` before?
Or missing the first char?

**Comment by alokg1019** [comment]
It's always missing the first char whenever the any function is named which contains a key word at the start. The update is not delayed I think , because if I change the name of the function other than this,  it  immediately updates on the UI without any character omission.

**Comment by jdarwood007** [comment]
![function list](https://cloud.githubusercontent.com/assets/732116/14188506/b9753c0a-f73d-11e5-9408-d50222381486.png)

I see the same issue as well using version 6.9.1

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/60b4aa6b75c60b436d1f3a539cd75956fbb98b3e
