### ISSUE TITLE
Incorrect coloring of javascript code inside html

### ISSUE THREAD

**Issue by GChuf** [notepad-plus-plus/notepad-plus-plus#9812]
### Description of the Issue
The title says it all - take a look at the picture also.
![npp](https://user-images.githubusercontent.com/42591821/116417145-4b9c3f80-a83b-11eb-9463-c9b7f596711f.png)

### Steps to Reproduce the Issue

1. use [Template Literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)  (`)
2. Add double slash inside
3. npp thinks this is a comment (green color is for comments)

### Expected Behavior
The color should stay black.

### Actual Behavior
String is of green color after the double slash

### Debug Information
Notepad++ v7.8.8   (64-bit)
Build time : Jun 23 2020 - 23:59:56
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1379
Current ANSI codepage : 1250
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

Additionally:
the text inside template literals appears black otherwise, and the brackets are in bold.
After adding one slash, the color changes to violet. I don't know what that is.
![npp2](https://user-images.githubusercontent.com/42591821/116417931-fe6c9d80-a83b-11eb-8a7b-20594301f51a.png)

**Comment by ArkadiuszMichalski** [comment]
Known Scintill/Lexilla bug https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4007, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3822#issuecomment-697275450. Close as duplicate.

@GChuf Next time put yuor code example inside \`\`\` and \`\`\` delimiters (do not use print screen). And you should upgrade your version of Notepad ++ (actual is 7.9.5).

**Comment by GChuf** [comment]
@ArkadiuszMichalski OK, got it ...
did someone from N++ team message the developers or scintilla? it seems the issue isn't going to be resolved anytime soon.

**Comment by pbarney** [comment]
Is this problem actually insurmountable? Can we get a definitive "wontfix" or is it that no contributors are interested in this issue? Maybe a "help wanted" label? Should we just expect any issue that references this problem to be immediately closed without comment?
