### ISSUE TITLE
Multi OS support

### ISSUE THREAD

**Issue by ccuser44** [notepad-plus-plus/notepad-plus-plus#9816]
I known NP++ depends on the Win32 API but cross platform support would be great.

NP++ for Linux and MacOS is a must!

I known the solution won't be easy but it is important regardeless. Maybe it shouldn't have such heavy reliance on the W32API?

**Comment by ccuser44** [comment]
why close it? cant you even consider it. or give any info regarding it?!?!?!?!?!?!

**Comment by mere-human** [comment]
There were some discussion about this in the past. Try searching the Community Forum. 
For example, this tread: https://community.notepad-plus-plus.org/topic/81/np-on-linux
Even Wikipedia has info about that:
> Notepad++ was built as a Microsoft Windows application; the author considered, but rejected, the idea of using wxWidgets to port it to the Mac OS X and Unix platforms.

https://en.wikipedia.org/wiki/Notepad%2B%2B

In my opinion, it would not be much different from rewriting the application from scratch (that is very difficult).
So few contributors decide to focus on stability and functionality of the existing platform.

**Comment by ccuser44** [comment]
Ok understandable. Thank you. :) However this should be said somewhere where it could be easily found

**Comment by mere-human** [comment]
> However this should be said somewhere where it could be easily found

https://en.wikipedia.org/wiki/Notepad%2B%2B
![image](https://user-images.githubusercontent.com/9664141/117624054-28e42200-b17d-11eb-8900-ffc6a6680f60.png)

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/SUPPORTED_SYSTEM.md
![image](https://user-images.githubusercontent.com/9664141/117624123-3bf6f200-b17d-11eb-8fcd-e6882979399d.png)

**Comment by ccuser44** [comment]
Well yes. I kinda didnt mean thah. What I meant was that it should be made clear that porting to other system isnt easy and wont be done in the near future

**Comment by sasumner** [comment]
>What I meant was that it should be made clear that porting to other system isnt easy and wont be done in the near future

If you search this issues list (which is a good thing to do before creating a new one), you will find many related issues that people have made, here are just a few I found with a quick search:

#108
#332
#6151
#7548

I'd bet there are many more.

**Comment by ArkadiuszMichalski** [comment]
It's worth adding this to the FAQ,

**Comment by ArkadiuszMichalski** [comment]
>I suppose it will provide an instantly linkable response to such issues, however. :-)

Yes, replying to the same thing deserves a [quick link](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/FAQ#support-for-systems-other-than-the-ms-windows-family).
