### ISSUE TITLE
Support kotlin programming language if possible

### ISSUE THREAD

**Issue by wo4chenkewen** [notepad-plus-plus/notepad-plus-plus#9818]
As kotlin programming language becomes more and more popular, so I wish the notepad++ can support kotlin language. 
                                                                                                                                                         Many thanks to notepad++ team

**Comment by mere-human** [comment]
There is no syntax highlighting for Kotlin in Scintilla (a component that is used in Notepad++). I've checked in SciTE 5.0.
So it seems, the only way to add it is to use [UDL](https://npp-user-manual.org/docs/user-defined-language-system/).

**Comment by ArkadiuszMichalski** [comment]
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3266.
