### ISSUE TITLE
[Feature Request] Copy Pathnames from Search Results window

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#9821]
I'd like to be able to copy the pathnames of the files with hits from a _Find in Files_ search.

I envision a right-click choice to do this, from the _Search results_ window's context menu, possibly like so:

![image](https://user-images.githubusercontent.com/30118311/116797087-bf468280-aaaf-11eb-913b-edcc38a70b4f.png)

Executing such an option would place any pathnames present in the _Search results_ window into the clipboard such that when they are later pasted, one pathname appears per line in the paste.

Of course, if files are "unnamed", they'd simply come across in the copy as, e.g. `new 3`.

### Debug Information
Request based upon functionality current to Notepad++ 7.9.5

**Comment by sasumner** [comment]
Another possible idea is to start grouping "special" copy commands under a common submenu, perhaps called "Copy Special" ?  Example:

![image](https://user-images.githubusercontent.com/30118311/116814595-c4dfaf00-ab27-11eb-82d2-db4ab7067983.png)

**Comment by donho** [comment]
@sasumner 
I think it's OK so far without sub-menu. We'll reorganize the menu when there are too many items, by hoping that this day will never come :)

**Comment by sasumner** [comment]
OK, I will do it without the submenu.  
But here are some future notes in case it is ever desired to have the submenu:

* Using a *Copy Special* submenu here emphasizes that not simply a pure copy is being done.  This might be considered important because when user sees *Copy Selected Line(s)* he may not realize that this is not going to be a copy like he intends, it is going to be "special".
* Doing the submenu like I showed above is extremely easy, here's how it was done for the screenshot demo:

```
tmp.push_back(MenuItemUnit(NPPM_INTERNAL_SCINTILLAFINDERCOPY, copyLines, TEXT("Copy Special")));
tmp.push_back(MenuItemUnit(NPPM_INTERNAL_SCINTILLAFINDERCOPYPATHS, copyPaths, TEXT("Copy Special")));
```
