### ISSUE TITLE
v7.9.5 installer: virustotal and metadefender showing malware

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/notepad-plus-plus#9825]
@donho ,

As reported in the Community Forum at https://community.notepad-plus-plus.org/topic/21082/virustotal-detects-a-malware-in-the-official-npp-7-9-5-installer-x64-exe, virustotal and metadefender are showing that the "zillya" scanner is marking the v7.9.5 x64 installer as malware:
* https://www.virustotal.com/gui/file/4881548cd86491b453520e83c19292c93b9c6ce485a1f9eb9301e3913a9baced/detection => Zillya => Trojan.Rozena.Win32.119520
* https://metadefender.opswat.com/results/file/0038e9c3d7b208b2f56a1b3b714cca86/hash/overview?lang=en => Zillya! => Trojan.Rozena.Win32.119520 as of Apr 30

Forum user "@Daniel-Fuchs" linked to 
* https://www.virustotal.com/gui/url/31b8b0d964ee218f1208e8c0130182677f07c750e77c856d28e4d4b04340c95a/detection => this scan shows clean, but it didn't run the Zillya scanner

According to Forum user "@b00kgrrl", this false-positive has triggered Windows Security to mark it as malware, and that user had to uninstall Notepad++ and stop using it.

This false-positive is meaning that people are not able to install/run Notepad++, which is a bad thing

**Comment by pryrt** [comment]
I just told https://www.virustotal.com/gui/file/4881548cd86491b453520e83c19292c93b9c6ce485a1f9eb9301e3913a9baced/detection to re-scan, and this time it came up clean, but the Zillya scanner is no longer listed... so presumably sites that still use the zillya scanner will continue to get false positives

**Comment by pryrt** [comment]
the metadefender is still using zillya, even when I ask for a re-scan.

And I don't know whether the "Windows Security" popup that the "@b00kgrrl" user identified will be using the zillya or if it has some separate false positive.

**Comment by mere-human** [comment]
I wonder what caused that and how can we fix it.

**Comment by donho** [comment]
@pryrt @mere-human 

The false-positive detection by some anti-virus software has been always the problem since longtime ago.
It's related to [NSIS installer that Notepad++ uses for packaging](https://nsis.sourceforge.io/NSIS_False_Positives).
I have no solution so far for that besides to not use NSIS anymore.

**Comment by dail8859** [comment]
Closing since it is for an old version.

**Comment by mikeycrawford** [comment]
Issue is still occurring with VT, Zillya and latest version of NPP - 8.4.9

https://www.virustotal.com/gui/file/6b170127061feb082ffd1b14309ef6d4a783df3c0fd51999e1786067731a49f3/detection

**Comment by misan** [comment]
Still happening nowadays (I understand this is not a NP++ issue).

![Image](https://github.com/user-attachments/assets/2034b4d5-eda7-4258-8f5d-e43795483c6a)
