### ISSUE TITLE
Notepad++ crashes when replacing in files

### ISSUE THREAD

**Issue by Zubastic** [notepad-plus-plus/notepad-plus-plus#9827]
### Description of the Issue
When I trying to replace one value with another (Replace in files).

### Steps to Reproduce the Issue

1.  Ctrl+H
2. Enter value for replacing
3. Replace in files

### Expected Behavior

All seached values are replaced.

### Actual Behavior

Notepad++ is stop working.

### Debug Information

Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Enterprise 2016 LTSB (64-bit) 
OS Version : 1607
OS Build : 14393.4169
Current ANSI codepage : 1251
Plugins : ComparePlugin.dll CSScriptNpp.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll

**Comment by sasumner** [comment]
Not enough information to attempt to reproduce the problem.
If more information is provided, will consider reopening.

**Comment by Zubastic** [comment]
What information I should provide to fix this issue?
