### ISSUE TITLE
Update CONTRIBUTING.md with bug reporting guidelines 

### ISSUE THREAD

**Issue by dail8859** [notepad-plus-plus/notepad-plus-plus#984]
Given the numerous bug reports with very limited information, it is difficult to triage them. Guidelines about how to report them would be helpful. As far as I know, there is no way to use a predefined template on Github when reporting issues (I think Google Code use to when it was still around). However the banner of "Please [review the guidelines](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md) for contributing to this repository." appears at the top when reporting bugs, so hopefully users will pay attention to this! 

I propose the CONTRIBUTING.md file be broken up into two sections. The first for bug reports, so that a simple user does not have to dig through the entire file. And the second section can be the text that is already there with a header labeling it for pull requests.

I think this needs to be as short and precise as possible so users do not get confused or feel overburdened. A few of the things I thought would be helpful would be some things like:
* Explain how to disable plugins to see if that is the cause *first*! 
* State that any bug related to a plugin that does not ship with Notepad++ (might be helpful to list them specifically) should be reported to their respective sites first.
* If it is indeed a bug with Notepad++ or one of its standard plugins, include Operating system info, Notepad++ version, and any other relevant info. 

This way we can always reference this section of the CONTRIBUTING.md file for reports that do not include enough information.

**Comment by donho** [comment]
@dail8859  Good point. 
Please modify CONTRIBUTING.md then I will accept your pull request.
