### ISSUE TITLE
Find Results copy no longer working

### ISSUE THREAD

**Issue by tbayart** [notepad-plus-plus/notepad-plus-plus#9840]
### Description of the Issue

When you perform search for all occurrences, it appear in the Find result window
In Find window you can copy a result by right clicking on the header (blue of green).
This copy the lines in the result into the clipboard.
On current version, this is no longer working, when you paste the text the pasted text is not what has been copied.
I tested on previous versions and found it working on version up to 7.9.1
Broken since 7.9.2

### Steps to Reproduce the Issue

1. Generate a search result using ie Find all in current document feature
2. Copy the results by Right clicking on a header (blue or green)
3. Open a new file
4. Use Paste command (Right click Paste or Ctrl+v)
Nothing happen if clipboard is empty, otherwise an older copied value is paste

### Expected Behavior

The copied lines should be paste without le "Line xxx" header

### Actual Behavior

The copied text is not paste, can be an older copied value or nothing

### Debug Information

Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.928
Current ANSI codepage : 1252
Plugins : AnalysePlugin.dll ComparePlugin.dll HexEditor.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll NppTextFX.dll XMLTools.dll 

![Clipboard01](https://user-images.githubusercontent.com/5262768/117461988-7890d680-af4e-11eb-97e4-45a119ef6a87.png)

**Comment by tbayart** [comment]
You're right, the screenshot is from the working 7.9.1 version
I updated the screenshot with 7.9.5 version

**Comment by sasumner** [comment]
OK, then, are you using the command I showed in yellow above?
From your new screenshot it appears (shown in blue) you are using the `Copy` command, which is not the correct command for what you seem to be trying to do.

**Comment by tbayart** [comment]
No, I don't use Copy Selected Line(s) which works 
I try to use Copy but it does not work anymore
To use Copy Selected Line(s) I have to select line first but when I paste I have an annoying header "Line xxx:" on each line
As explained in the issue, using the Copy feature on version 7.9.1 do the job
The same cinematic not longer works since 7.9.2

**Comment by sasumner** [comment]
>To use Copy Selected Line(s) I have to select line first but when I paste I have an annoying header "Line xxx:" on each line

No, this does not result from _Copy Selected Lines(s)_, only from plain _Copy_.
And you can, but you don't have to, make a selection first.

>using the Copy feature on version 7.9.1 do the job

In this older version, yes _Copy_ was different.
That functionality is now in the newer _Copy Selected Line(s)_ command.
Things change in software, to make it better -- you can't complain about such a change -- well, you can, but no one is going to listen or think it is a problem with the software.

------------------------------------------------------

Examples of choosing _Copy Selected Line(s)_ where a red "dot" shows the right-click point:

### Example 1:

![image](https://user-images.githubusercontent.com/30118311/117506657-f4d9e880-af53-11eb-83a4-1591a7c371a3.png)

results in this text in the clipboard:

`c`

### Example 2:

![image](https://user-images.githubusercontent.com/30118311/117506793-2fdc1c00-af54-11eb-81ef-861acf8416fc.png)

results in this text in the clipboard:

```
bb
```

### Example 3:

![image](https://user-images.githubusercontent.com/30118311/117506934-66199b80-af54-11eb-98cf-bb3a712aa7d0.png)

results in this text in the clipboard:

```
a
bb
c
```

### Example 4:

![image](https://user-images.githubusercontent.com/30118311/117507080-995c2a80-af54-11eb-9edd-9a2e03351ffa.png)

results in this text in the clipboard:

```
a
bb
```

So I see no issue here, so I'm closing this issue.

You can refer to the user manual in the "Searching" section for more information on how this feature works.

**Comment by sasumner** [comment]
>You can refer to the user manual in the "Searching" section for more information on how this feature works.

Oops, the manual is out of date about this.  It is still describing _Copy Selected Line(s)_ functionality as _Copy_.
I will create an issue to fix this.

**Comment by sasumner** [comment]
>I will create an issue to fix this.

See https://github.com/notepad-plus-plus/npp-usermanual/issues/210

**Comment by tbayart** [comment]
I see, tested and validated, thank you for pointing out the issue with manual.
and thank you for explanation,, I use a lot this feature so I'm glad it's just a misunderstanding
