### ISSUE TITLE
Notepad++ update dialog (GUP.exe) is running even after closing Notepad++.

### ISSUE THREAD

**Issue by vamsiikrishnaak** [notepad-plus-plus/notepad-plus-plus#9841]
### Description of the Issue
When we try to update Notepad++ and if no updates are available, a dialog is displayed. If notepad++ is closed, this dialog remains open and does not close automatically. 
I am not sure if this is expected behavior. But I feel that when notepad++ is closed, all the dialogs opened from it should also be closed. All other dialogs displayed from clicking "Debug Info..." or "About Notepad++" are closed automatically.

### Steps to Reproduce the Issue
1.  Click on "Update Notepad++" from the menu bar under "?".
2.  A dialog with the title "Notepad++ update" and a close button is displayed.
3.  Close the main Notepad++ window.
4.  Observe that the Notepad++ update dialog is still displayed.

### Expected Behavior
The Notepad++ update dialog should be closed automatically when Notepad++ is closed.

### Actual Behavior
Notepad++ update dialog is still open and the corresponding process "GUP.exe" can be seen in the list of processes in Task Manager.

### Debug Information
Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home Single Language (64-bit) 
OS Version : 2009
OS Build : 19043.964
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

![GUP](https://user-images.githubusercontent.com/17508246/117461734-86a12000-af6b-11eb-8f10-699355231c7f.png)
![TaskManager](https://user-images.githubusercontent.com/17508246/117461740-87d24d00-af6b-11eb-87d6-4f0e8aa064b8.png)

**Comment by wcjcn** [comment]
I think you can simply close the GUP.exe forcely if it's not usually appear.

**Comment by mere-human** [comment]
I think it would be good if Notepad++ closed the GUP on shutdown.
I have an idea how to fix it.

@sasumner What do you think?

Also, it is clear that the "No update" dialog should be closed. 
But what to do when there is an update and Notepad++ is closed?
![image](https://user-images.githubusercontent.com/9664141/117550696-4b295300-b04a-11eb-827a-8c9cd28d91d9.png)
I suppose, in this case, we should leave this dialog as is.

**Comment by sasumner** [comment]
>What do you think?

You haven't elaborated on your idea, but...sure! :-)

**Comment by mere-human** [comment]
@sasumner 

> You haven't elaborated on your idea, but...sure! :-)

So the idea is, we remember the process handle of the `gup.exe`.
Upon Notepad++ closing, we check if `gup.exe` is still running.
If it is, then we find its main window.
If it's a tool window (like "No update is available"), then we send a message IDCANCEL to it (same as pressing the "Cancel" button).
If it's any other window, we don't touch it.

Actually, I have a working prototype. But I'm trying to figure out if it's safe enough for the case when `gup.exe` closes Notepad++ for applying the update.

**Comment by mere-human** [comment]
@sasumner Can you assign this to me?

**Comment by donho** [comment]
Updater (GUP.EXE) is another executable binary. So it's hard to keep it under control of Notepad++ once it's launched.
User can click OK button to close it anyway.
