### ISSUE TITLE
 Sort the search results which has more than one file by the number of hits in descending or ascending order

### ISSUE THREAD

**Issue by wcjcn** [notepad-plus-plus/notepad-plus-plus#9842]
Dear friends on GitHub, in some large projects, sometimes there are hundreds of files containing keyword, maybe the hits of keyword is an important for people to find what he or she want quickly. 

I want to sort the search results which has more than one file by the number of hits in descending or ascending order. 

I think this can be added at right-click menu " Descending hits" and "Ascending hits" and "Default hits".

It's my first time to submit an issue on GitHub, so I'm not very clear about the format here. English is not my native language either, so please bear with me.

I think this is a very good idea and suggestion, and would very much like to see the professionals see my suggestion. Thank you all and have a great life.
![example](https://user-images.githubusercontent.com/30321584/117540827-968c3300-b043-11eb-9663-0354a6701e22.png)

**Comment by wcjcn** [comment]
We hope that people who have demand for this feature will leave more comments and guidance so that professionals can pay attention to this issue, thank you all.

**Comment by wcjcn** [comment]
@sasumner  Can you help me to make this issue known by more professionals . Thank you!

**Comment by wcjcn** [comment]
@donho @sasumner @Uhf7 @mere-human @kubalav @conky77 @chcg @ArkadiuszMichalski @schnurlos @rddim @Patriccollu @GOLEM777 @yasmise @a-polivanchuk   @Tmp341 @jofon @xomx @Edditoria @el-coder-sb @adzm

Dear friends, can you help me to see if this feature request can be implemented? I think its very useful. Thank you!

**Comment by wcjcn** [comment]
> > Can you help me to make this issue known by more professionals
> 
> How would I do THAT ?? :-)

Hello, just ask some professionals you konw to look if this feature is possiable and usefual. I request some professionals to help me adjust if this feature can be realized! Wish we good luck.

**Comment by Edditoria** [comment]
@wcjcn Hey you have to learn how Github community work. Reviewing an issue or feature request could take days.

There are ton of people in public viewing your issue since it is opensource. Not a good idea to @ any people. If there are people interested in your issue, they will do Pull Request someday.

If you want some attention, go to social networks, chatrooms, forums. Post the link of this issue in there. Discuss with other user for opinions.

p.s. I'm not a code contributor in this repository :)

**Comment by mere-human** [comment]
@wcjcn What is exactly wanted in this feature request? So that the files with more hits are shown first?
I'm not very familiar with that area.
I'm almost sure that @sasumner knows more about the Search Results view.

**Comment by wcjcn** [comment]
> @wcjcn Hey you have to learn how Github community work. Reviewing an issue or feature request could take days.
> 
> There are ton of people in public viewing your issue since it is opensource. Not a good idea to @ any people. If there are people interested in your issue, they will do Pull Request someday.
> 
> If you want some attention, go to social networks, chatrooms, forums. Post the link of this issue in there. Discuss with other user for opinions.
> 
> p.s. I'm not a code contributor in this repository :)

 I am first time to make a issue, not familiar with this workflow. Thank you for your advice, I will make more attention in other.

> @wcjcn Hey you have to learn how Github community work. Reviewing an issue or feature request could take days.
> 
> There are ton of people in public viewing your issue since it is opensource. Not a good idea to @ any people. If there are people interested in your issue, they will do Pull Request someday.
> 
> If you want some attention, go to social networks, chatrooms, forums. Post the link of this issue in there. Discuss with other user for opinions.
> 
> p.s. I'm not a code contributor in this repository :)

 I am first time to make a issue, not familiar with this workflow. Thank you for your advice, I will make more attention in other.

**Comment by wcjcn** [comment]
> @wcjcn Hey you have to learn how Github community work. Reviewing an issue or feature request could take days.
> 
> There are ton of people in public viewing your issue since it is opensource. Not a good idea to @ any people. If there are people interested in your issue, they will do Pull Request someday.
> 
> If you want some attention, go to social networks, chatrooms, forums. Post the link of this issue in there. Discuss with other user for opinions.
> 
> p.s. I'm not a code contributor in this repository :)

 I am first time to make a issue, not familiar with this workflow. Thank you for your advice, I will make more attention in other.
