### ISSUE TITLE
Rename Current Tab is limited to 20 characters

### ISSUE THREAD

**Issue by nmatt** [notepad-plus-plus/notepad-plus-plus#9849]
### Description of the Issue

When using File > Rename... on a yet unsaved file ("Rename Current Tab"), the text input for the new name is limited to 20 characters. There doesn't seem to be a good reason for that, because file names (which serve the same purpose after saving) are not limited to 20 characters. It is often useful to give scratch documents a description that may be longer than 20 characters.

### Steps to Reproduce the Issue

1.  File > New
2.  File > Rename...
3.  Type characters into the New Name text input of the Rename Current Tab dialog

### Expected Behavior
It should be possible to enter more than 20 characters for the new name. A reasonable limit would be 255 characters.

### Actual Behavior
It is not possible to enter more than 20 characters for the new name.

### Debug Information

Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.928
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by donho** [comment]
@sasumner 
The spammer has been banned. I guess you've no privileges to ban people. But if you have, you can just do it. Otherwise just let me know like this time.

**Comment by nmatt** [comment]
@sasumner: Persistent scratch documents are a great feature of Notepad++. It's exactly because you don't have to deal with filesystem paths. Instead you conceptually have "document open in Notepad++" <=> "document exists". Another major benefit is that the scratch documents are easily distinguishable from permanent files in the document switcher, because they don't have paths. You immediately see what type of document it is (scratch vs. permanent file). The scratch documents I use mostly have a lifetime of just a few days, but I usually have over a dozen open at any given time, over several projects I'm working on. The 20 character limit is often too low if I name them "{project} - {topic}".

Thanks for the script idea, but it does have drawbacks (like paths visible in the document switcher, see above), and it seems weird that the arbitrary 20 character limit can't just be relaxed a bit. It probably made sense in the past when tab labels were limited to 20 characters, but that limitation doesn't exist today, and so this now seems like an inconsistency of how document names are handled.

**Comment by donho** [comment]
@nmatt 
What length limit is reasonable to you?

**Comment by nmatt** [comment]
@donho: Thanks for coming back to this. I would make the length limit as generous as possible. Windows has a path length limit of 260 characters [1]. (Renaming a file in file explorer also applies that limit.) The Notepad++ scratch documents are stored under "%APPDATA%\Notepad++\backup\<document name>@<timestamp>", so the resulting length restriction is _length_(%APPDATA%) + 18 + _length(<document name>)_ + 18 ≤ 260. The length of %APPDATA% is usually (but not necessarily) 25 + _length(username)_. Reserving let's say 64 characters for %APPDATA%, that would leave 260 - 64 - 36 =160 characters for the document name. So I would suggest to programmatically limit the length to _min(160, 224 - length(%APPDATA%))_.

[1] https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation

**Comment by alankilborn** [comment]
> ...that would leave 260 - 64 - 36 =160 characters for the document name. So I would suggest to programmatically limit the length to _min(160, 224 - length(%APPDATA%))_.

It is not surprising that a suggestion like that got totally ignored.

**Comment by donho** [comment]
@nmatt 
The length of 63 characters is long enough IMO.

@alankilborn 
You don't have to be unpleasant in the issue tracker. You can choose to NOT do your support.
