### ISSUE TITLE
"Ⅷ" not rendering correctly after tabulator

### ISSUE THREAD

**Issue by masagrator** [notepad-plus-plus/notepad-plus-plus#9855]
### Description of the Issue
When pasting Ⅷ in one line with tabulator that is somewhere before this character, instead of showing this character it shows 𖡄. 

### Steps to Reproduce the Issue
1. Create New file
2. Use Tab
3. Paste "Ⅷ"

### Expected Behavior
Show "	Ⅷ"

### Actual Behavior
Instead of showing "	Ⅷ" it will show "	𖡄"

### Debug Information
Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19043.964
Current ANSI codepage : 1250
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll 

###Additional Info
This doesn't happen for numbers Ⅰ-Ⅶ and Ⅸ-Ⅹ, only happens for "Ⅷ"
If "Ⅷ" is pasted before tabulator, it's showed correctly.
Coding used in this case is UTF-8.

**Comment by sasumner** [comment]
See if this helps:  [INCORRECT CHARACTER RENDERING](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/FAQ#incorrect-character-rendering)

**Comment by masagrator** [comment]
Yeah, it works. Sadly it's too slow to have it enabled for me. :D
