### ISSUE TITLE
JS Autocomplete keywords are too old

### ISSUE THREAD

**Issue by Sashank999** [notepad-plus-plus/notepad-plus-plus#9858]
### Description of the Issue
JavaScript auto-completion is too old

### Expected Behavior
Npp is open-source, so I will do a PR updating them to some of the latest features in latest ECMA Script Specification.

### Debug Information
Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2004
OS Build : 19041.928
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
Please provide citation for the specification used.
It makes review/acceptance easier.

**Comment by Sashank999** [comment]
> Please provide citation for the specification used.
> It makes review/acceptance easier.

I am really really sorry I didn't see that you would comment on the issue instead of the PR. I was actually checking the PR.
It actually contains some most common standard features and also ES6 ones.

**Comment by Sashank999** [comment]
Just updated it to ES 2020.

P.S. Just asking, is it mandatory to create Issue even for language autocompletion PRs ?

**Comment by sasumner** [comment]
>P.S. Just asking, is it mandatory to create Issue even for language autocompletion PRs ?

Yes, that's where discussion such as the above (and the below) happens.

>Just updated it to ES 2020.

Is that your "citation of specification"?
If so, it doesn't help too much because I don't know what "ES 2020" is.
We're looking for a website link here where the specification is clearly shown.
The less research you make us do, the more likely your issue will be dealt with.
Probably this is all very clear to you, but to someone that doesn't ever do JS, it is not.

**Comment by Sashank999** [comment]
I'm really sorry. I thought you are a JS dev too.

Anyway, here is the official specification.
https://262.ecma-international.org/11.0/
A wikipedia link to the language specification. It also has the main features that have been added along the previous ECMAScript versions too:
https://en.wikipedia.org/wiki/ECMAScript#ES2020
V8, the JS Engine in Chrome, also has some features ordered by tags ES2015, ES2018, ES2019, ES2020... :
https://v8.dev/features/tags

The thing is that we shorten "ECMA Specification" to "ES" and suffix the specification's edition, and that worked until ES5.
But after ES5, we instead suffix the year of the specification's release to "ES". But ES6 and ES2015 are the same. And thats where the year convention began but we still refer ES6 for the 2015's edition.

**Comment by Sashank999** [comment]
Are there any other things I need to specify to get my PR accepted ?

**Comment by ArkadiuszMichalski** [comment]
You also add some things from DOM: https://dom.spec.whatwg.org/.

**Comment by Sashank999** [comment]
> You also add some things from DOM: https://dom.spec.whatwg.org/.

Added them too.
