### ISSUE TITLE
Suggestion: Add the name of the parent directory to the tab name for CMakeLists.txt files

### ISSUE THREAD

**Issue by ongamex** [notepad-plus-plus/notepad-plus-plus#986]
Add the name of the parent directory to the tab name for CMakeLists.txt files.
Working with multiple CMake files gets really tricky, becase CMake forces you to use CMakeLists.txt.

**Comment by donho** [comment]
It's not a generic way to do it.
You can using tip (by hovering on tab) to get the full file path.
