### ISSUE TITLE
Name the next version as "Clockwise"

### ISSUE THREAD

**Issue by frog-no-1** [notepad-plus-plus/notepad-plus-plus#9874]
### Description of the Issue

Advise to name the next version as "Clockwise" in memory of Taiwan people's great achievement in WH (Wan Hua) virus period, under the leadership of Shizhong Chen ("Clockwise"). 

### Steps to Reproduce the Issue

1. Just do it.

### Expected Behavior

Name the next version as advised.

### Actual Behavior

The owner close this issue ?

### Debug Information

I really appreciate your head portrait, some people are covered their eyes by their government's lies! 

Hope you also appreciate mine.

**Comment by frog-no-1** [comment]
@sasumner  This is non of your business, please stay far from this issue, thanks a lot. @donho Would you like to fix this issue by yourself ? Errr....

**Comment by frog-no-1** [comment]
As long as you want to make this project a political one, why don't we have fun with it ?

**Comment by sasumner** [comment]
@donho This person is another one to ban.

**Comment by frog-no-1** [comment]
@sasumner Ban? Where is your free speech sprite? I'm so scared, Errr.... so you also support this? Or you think Taiwan's performance is not good enough and mark @donho as come from a shit place ?

![image](https://user-images.githubusercontent.com/84258538/118397021-b4c9e280-b684-11eb-94f9-2f9d3222f399.png)

And have your mum ever tough you, it is not polite to bark when others are talking, the little coward? 

If you do not agree with me, perhaps you could still publish two versions, one for brave Taiwan and one for shit Taiwan.

**Comment by frog-no-1** [comment]
@donho @sasumner  Before this project, I have never seen an open source project got involve in politics. Your guys are just pee on the open source sprite.  Shame for you! 

This account is deprecated, see you on Frog-no-2 if I'm willing to do so one day. :-)
