### ISSUE TITLE
Most Edit menu items are inaccessible via keyboard

### ISSUE THREAD

**Issue by debiedowner** [notepad-plus-plus/notepad-plus-plus#9875]
In some Notepad++ menus, no items have hardcoded access keys (e.g. `View`, `Encoding`, `Language`, `Settings`, `Tools`,...), so you activate them by pressing the key for the first letter of the item (multiple times, if more than such items exist). In `File`, `Edit` and `Search` menus, some items have hardcoded access keys, and others don't; so the underlined letters activate them, no matter the first letters of other items.

I find the interwoven way this is done in the `Edit` menu particularly problematic. E.g. the `Line Operations` item has the most subitems in any Notepad++ menu, most of which don't have keyboard shortcuts; and even if you assign keyboard shortcuts to all those 23 items, it is difficult to remember all 23 of them so you would still need to frequently open the menu. But it's not possible to access the menu by pressing `Alt+E` and then `L`, because doing so activates the `Select All` item, which has the `L` key hardcoded into it. And what's worse, the `Line Operations` item is right on the middle of the `Edit` menu, so the only way to reach it with keyboard is, pressing `Alt+E` and then pressing `Down arrow` 11 times, or `Up arrow` 13 times!

To me, the exact opposite of the current behavior would make more sense, where the mundane items in the first two sections of the `Edit` menu do not have hardcoded access keys, and the items in the later sections should have access keys instead. Alternatively, hardcoded access can be removed from all, so that only the first letters are used to access all items (though 10 items start with `C` in English localization, so those ones would be a bit overloaded). Alternatively, hardcoded access keys can be added to all items.

Here is an example of what those alternatives might look like:

![Edit menu access key alternatives](https://user-images.githubusercontent.com/24410225/118388083-f3cb4a00-b62a-11eb-8185-c0d6e82ee034.png)
*1 (current menu), 2 (opposite), 3 (none), 4 (all)*

I called the items in the first two sections 'mundane' as I can't imagine there being any significant number of keyboard users who "Select All", by pressing `Alt+E` and then `L`, instead of just `Ctrl+A`. I would assume that everybody who is proficient enough with keyboard shortcuts to know to activate menus with `Alt` keys, is already also familiar with and uses the `Ctrl+A` shortcut, which are standard across all programs. I am sure that there are mouse users who do very much use the `Edit -> Select All` menu item, but they would be using the mouse to select it. (In fact, they wouldn't even know that `L` is the access key for the item, since underlined keys don't appear if you click `Edit` with mouse instead of `Alt+E`, and mouse users wouldn't have bothered with activating the Windows ease of access setting "Underline access keys when available".) Similarly for other hardcoded shortcuts; the `Copy` item blocks access to items like `Convert Case to` which includes many items with difficult to remember/nonstandard shortcuts. And it is hard to imagine anybody using `Alt+E` and then `C` to copy things; they would either use `Ctrl+C` if they prefer the keyboard, or click `Edit` and then `Copy` (or the toolbar button) if they prefer the mouse.

Even though I would personally prefer **2** for this reason, I thought it might be strange not to have access keys only for the initial items (and I was also wary of breaking existing workflows, even though I assume them to be extremely rare), so I made a pull request for **4**. (While at it, I also added access keys to the items in the `File` and `Search` menus that lacked them.) I think the alternative **3** would also be an improvement over the existing situation, if that will be a more acceptable solution. And whichever approach is preferred, I can then modify the `english.xml` file accordingly as well.

**Comment by RockyTDR** [comment]
@debiedowner In my opinion, option `3` (no hardcoded access keys) is the best way. Like you said, option `1` and `2` interfere with `3`, while `4` requires all entries to be keybound.
As a translator, I don't like to have to assign acces keys, especially because sometimes, the letter used in English is not available in the target language (e.g. in Dutch, "`C`opy" = "Kopiëren") or the position of the character doesn't make any sense ("`E`dit" = "B`e`werken")

I only noticed yesterday (because of your pull request 😅) that option `4` actually works! So I think that, for the Dutch translations, I'm going to remove all access keys so option `4` can be fully used.

**Comment by donho** [comment]
@RockyTDR 
> As a translator, I don't like to have to assign acces keys, especially because sometimes, the letter used in English is not available in the target language (e.g. in Dutch, "Copy" = "Kopiëren") or the position of the character doesn't make any sense ("Edit" = "Bewerken")

It's not mandatory. The access key should be conventional among the applications.
