### ISSUE TITLE
Suggestion not to truncate find and replace history lists on relaunch (older entries also may be needed) and to increase their length to 100 entries

### ISSUE THREAD

**Issue by vsl7** [notepad-plus-plus/notepad-plus-plus#9882]
Suggestion not to truncate find and replace history lists on relaunch (older entries also may be needed) and to increase their length to 100 entries

**Comment by sasumner** [comment]
In this section of the user manual:
https://npp-user-manual.org/docs/preferences/#preferences-for-advanced-users

is shown a line in config.xml like this:

`<FindHistory nbMaxFindHistoryPath="10" nbMaxFindHistoryFilter="10" nbMaxFindHistoryFind="10" nbMaxFindHistoryReplace="10" ...`

You may change `nbMaxFindHistoryFind` (with Notepad++ closed and using notepad.exe) to be a maximum of 30.

We think 30 is enough of a maximum.
