### ISSUE TITLE
Could Notepad++ remember last save directory?

### ISSUE THREAD

**Issue by aybe** [notepad-plus-plus/notepad-plus-plus#9885]
### Description of the Issue

Each time you start the application and save a file, it offers to do so at `C:\Program Files (x86)\Notepad++`.

Couldn't the software remember the last save directory that was used ?

Maybe it could offer an option `default save directory` that could be `Desktop` or `Documents` by default.

Could be like the following:
1. at first run on user machine, offer to save in that new `default save directory` option
2. wherever used saved, keep that location in application settings file
3. next time the user saves a file, the file dialog would open at that previously saved location

### Debug Information

Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.985
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll DSpellCheck.dll JSLintNpp.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppXmlTreeviewPlugin.dll Tidy2.dll XMLTools.dll

**Comment by aybe** [comment]
Woops, I should have checked beforehand, actually, the software indeed offers such option but it doesn't work: #9767

**Comment by mere-human** [comment]
@aybe The fix #9767 will be available in the next version, so stay tuned!

**Comment by aybe** [comment]
Thank you
!
