### ISSUE TITLE
Middle-click autoscrolling doesn't work.

### ISSUE THREAD

**Issue by Puliping** [notepad-plus-plus/notepad-plus-plus#9887]
### Description of the Issue

Clicking the middle-mouse button doesn't turn on the "autoscroll" feature (where you simply move the mouse to scroll the page, instead of using the mouse wheel).

### Steps to Reproduce the Issue

1. Open a file, preferably long enough to need scrolling.
2. Click the middle mouse button.
3. No autoscroll.

### Expected Behavior

Autoscrolling UI (circle with arrows) shows up, and moving the mouse scrolls the page.
Example:
![image](https://user-images.githubusercontent.com/5997350/118827764-0e9ff780-b893-11eb-9401-fa3277cc0637.png)

### Actual Behavior

Nothing happens.

### Debug Information

Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19042.985
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll HexEditor.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment]
Was asked earlier and rejected: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8275, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1154, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/695.

**Comment by sasumner** [comment]
...and so again...

**Comment by Puliping** [comment]
Alright, fair enough. Could I get some insight into why it won't be implemented, though?
Couldn't really see any justification in the linked issues or those referenced in them.

**Comment by mere-human** [comment]
I guess, because it doesn't work in Scintilla. I've just checked in SciTE. But that's just an assumption.

**Comment by Kyogre** [comment]
Hi everybody! There is [some AHK script](https://www.autohotkey.com/boards/viewtopic.php?p=55520#p55520) which adds autoscroll to wheel middle click. Even has acceleration setting. Works pretty good for me.

**Comment by Layarion** [comment]
what in the actual f? this elon hating c sucker team has time to hate on him but not include basic mouse features that this is the only program i know of atm that doesn't have this feature???

**Comment by SysAdminDoc** [comment]
This is a must have feature. Clicking on the scrollbar to navigate feels archaic.

**Comment by xomx** [comment]
> hating c sucker team

Wouldn't it be better to read carefully what was already [written](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/16056#issuecomment-2585854349) about the source of this issue (`it's a Scintilla library component issue`) than to post childish comment? (BTW, since when is someone with a different opinion on something called a hater or a sucker?)
