### ISSUE TITLE
Default .md README editor styles is unreadable in darkmode currentline

### ISSUE THREAD

**Issue by OzBob** [notepad-plus-plus/notepad-plus-plus#9890]
Set theme to Dracula
Open .md README file
click on any line
Black lettering on Black background
Editing Dracula Theme does not work
Editing userDefineLang.xml does not work.
Sugested solution: https://github.com/Edditoria/markdown-plus-plus

### Debug Information
Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.985
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll HexEditor.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll 

![image](https://user-images.githubusercontent.com/1796771/118947131-9c5e0e80-b989-11eb-9b0b-546ae1c4e81b.png)

**Comment by thomassmith311** [comment]
This is a general issue with Markdown files in Notepad++ with any theme but the default (though it shows up most clearly on dark themes). Issue has already been pointed out: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9649

**Comment by sasumner** [comment]
Closing as duplicate.
