### ISSUE TITLE
Error when using plugin: Copy Text With Syntax Highlighting in HTML language

### ISSUE THREAD

**Issue by Otteko** [notepad-plus-plus/notepad-plus-plus#9891]
### Description of the Issue
When using Copy Text With Syntax Highlighting, an error message: "Access violation" from "PluginsManager::runPluginCommand Exception" appears when a clickable URL is present in the selected text

### Steps to Reproduce the Issue

0. Set language to HTML (Language -> H -> HTML)
1. Add in any URL, make sure N++ detects it as clickable (Non clickable links do not reproduce the issue)
2. Select the url
3. Right-click -> plugin commands -> Copy Text With Syntax Highlighting

### Expected Behavior
The clipboard would contain the text as is rendered by N++ including syntax highlighting

### Actual Behavior
Error message: "Access violation" from "PluginsManager::runPluginCommand Exception" appears when a clickable URL is present in the selected text

### Debug Information
Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : D:\Programs\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll **NppExport.dll**

**Comment by sasumner** [comment]
Indeed with the STR and 7.5.6 I get:

![image](https://user-images.githubusercontent.com/30118311/119000710-58ebac00-b959-11eb-9f5b-ea7211456161.png)

Suggested resolution:  Try newer version of Notepad++ than 7.5.6.
I tried 7.9.5 and obtained the "Expected Behavior".

**Comment by Otteko** [comment]
I didn't realize I was so far behind on versions 😬

Updating has solved the issue for me
