### ISSUE TITLE
Notepad ++ and Pretty Print (XML Only with Line Breaks) not working

### ISSUE THREAD

**Issue by sebbyv** [notepad-plus-plus/notepad-plus-plus#9907]
When I try to use the latest version of Notpad++ with XML Tools > Pretty Print (XML Only with Line Breaks)  I get the following error: Errors detected in content. please correc them before applying pretty print
I get this regardless of the content.

I do have a machine that has Notepad 7.3.1 with this plugin and it is working. I don't see this version avalable on the website though.

### Steps to Reproduce the Issue

1. Download NotePad++
2. Install XML Tools
3. Try and use Pretty Print (XML Only with Line Breaks)

### Expected Behavior
Change line format

### Actual Behavior
Get the following error: Errors detected in content. please correc them before applying pretty print

### Debug Information

7.7.9

Notepad++ v7   (32-bit)
Build time : Sep 21 2016 - 22:00:56
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll XMLTools.dll

**Comment by mere-human** [comment]
Works for me.

XML Tools 3.1.1.1

Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.985
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll HexEditor.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppMarkdownPanel.dll NppTextFX.dll PythonScript.dll XMLTools.dll 


![image](https://user-images.githubusercontent.com/9664141/119564923-fc055100-bdb1-11eb-86b9-a02f93348792.png)

**Comment by mere-human** [comment]
Also, usually plugin bugs are reported to the corresponding plugin page.
![image](https://user-images.githubusercontent.com/9664141/119565106-35d65780-bdb2-11eb-9ef8-92c37c06e908.png)

**Comment by sasumner** [comment]
>plugin bugs are reported to the corresponding plugin page.

Yes, go there first; if something ends up being a bug in Notepad++ itself, come back here.
