### ISSUE TITLE
[FR] Switch programming language to Powershell for .psm1/.psd1-files

### ISSUE THREAD

**Issue by vhsol-cn** [notepad-plus-plus/notepad-plus-plus#9912]
### Description of the Issue
Programming language is not switched to Powershell for .psm1-/.psd1-files

### Expected Behavior
Programming language should switch to Powershell for .psm1-/.psd1-files

### Actual Behavior
Manually switching programming lanuguage to Powershell is required for .psm1-/.psd1-files.

### Debug Information
Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.985
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppXmlTreeviewPlugin.dll XMLTools.dll

**Comment by ArkadiuszMichalski** [comment]
You can find your `langs.xml` config file and add that extension in this line:
```xml
<Language name="powershell" ext="ps1 psm1" commentLine="#" commentStart="&lt;#" commentEnd="#&gt;">
```
The only question is whether it shouldn't be done by default.

**Comment by ArkadiuszMichalski** [comment]
More info:
https://learn.microsoft.com/en-us/powershell/scripting/developer/module/how-to-write-a-powershell-module-manifest?view=powershell-7.3
