### ISSUE TITLE
Add Discord Rich Presence 

### ISSUE THREAD

**Issue by darhanger** [notepad-plus-plus/notepad-plus-plus#9915]
### Description of the Issue
Title explains all. I want you to add Discord Rich Presence support.

**Comment by sasumner** [comment]
See #4787

**Comment by MikeCoder96** [comment]
I've created a plugin for notepad++
https://github.com/MikeCoder96/NotePad-Discord-Rich-Presence-Plugin
I hope in community contributions ❤️
