### ISSUE TITLE
Search and replace no longer allows you to replace with white space (tab and line returns) 

### ISSUE THREAD

**Issue by WolfieXIII** [notepad-plus-plus/notepad-plus-plus#9916]
### Description of the Issue
Find and replace - recent changes broke the ability to replace with whitespace characters 

### Steps to Reproduce the Issue
1.  Open the document you want to insert white space on a searchable pattern
2.  Try and paste white space characters into the replace box. 
3.  Fail miserably and curse your life for one of the more useful features not working now. 

### Expected Behavior
Be able to paste white space (specifically tabs and line returns) into the replace with field and perform a search and replace with those characters 

### Actual Behavior
What used to work no longer works and you cry.

**Comment by sasumner** [comment]
You didn't specify your version information via the _Debug Info_ request in the issue template, so your issue cannot be processed further.

But...Notepad++ has never allowed multi-line data to be pasted into the _Replace with_ box.
You may do such a replacement by using Regular expression search mode or Extended search mode and using `\r` for carriage return and `\n` for linefeed characters when you need line-endings in the replacement data.
