### ISSUE TITLE
Saving find/replace macro isn't possible

### ISSUE THREAD

**Issue by mslonik** [notepad-plus-plus/notepad-plus-plus#992]
Saving even simple macro in Notepad++ ver. 6.8.3 is no longer possible. To prove it I've removed from my system all macros by removing the file C:\Users\(...)\AppData\Roaming\Notepad++\shortcuts.xml and restarting Notepad++. Next I've created the following text file:

fikuCRLF
mikuCRLF

Next I started to record macro. From menu Find I've chosen Replace and put some commands to replace CRLF with LF (\r\n replace with \n, extended mode). Next I've ordered to stop recording of macro and save current macro (named "kilo"). Unfortunately the file C:\Users\(...)\AppData\Roaming\Notepad++\shortcuts.xml wasn't updated. The macro name ("kilo") was visible in menu only as long as Notepad++ was running. When Notepad++ was closed and reopen, macro was no longer visible. My conclusion is that macro recording is no longer working as expected, so I've submitted a bug. There is already the bug #968 which is prety similar, but it seems that its author didn't notice that recording of macros doesn't work at all.

**Comment by naiveknave** [comment]
I've updated to 6.8.3 and my original problem is still the same. I haven't been able to reproduce what you describe here - my macros get save just find and persist after n++ has been closed and opened again.

Something is *seriously* wonky with this...

**Comment by mslonik** [comment]
Today I reinstalled version 6.8.3 and tried again. I've still the same problem: no way to record any macro at all, no matter what combination of options chosen from a menu I choose, I can't record it - after reopening of n++ all is lost.
