### ISSUE TITLE
Make Notepad++ compilable with VS2019

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#9922]
Currently Notepad++ is built with VS2017.
It's time to switch to VS2019 for Notepad++ future versions.

**Comment by donho** [comment]
@chcg 
I guess you have tried it and made it. If yes, could you create a PR for it please?
I did try, but I didn't make it.

**Comment by mere-human** [comment]
I use VS2019 to build Notepad++. It works pretty well.  I've heard @sasumner uses VS2019 as well.
To do so, I simply installed VS2017 build tools in VS2019:
![image](https://user-images.githubusercontent.com/9664141/120101749-3d9a5100-c150-11eb-8caa-c16c68c72c5e.png)

To use VS2019 by default, I think, one has to switch the Platform Toolset.
![image](https://user-images.githubusercontent.com/9664141/120101681-ebf1c680-c14f-11eb-92d1-fc96d7d87101.png)

**Comment by sasumner** [comment]
What I do (and what I've always done since I never had VS2017):

* change _Platform Toolset_ (as @mere-human mentions) -- but I don't install v141, I just change the setting to v142
* change _Treat Warnings As Errors_ to _No_

Perhaps if I'd ever installed v141, I would not have had to change the warnings-as-errors setting?

**Comment by donho** [comment]
@mere-human @sasumner
Thank you for the reply. 
I suppose that you install VS2019 upon your VS2017? 
I download VS2019 community in my new laptop, and my settings screen (for SciLexer) has less options:  
![image](https://user-images.githubusercontent.com/90293/120200421-9b986880-c224-11eb-95f3-80df548830be.png)

And it gives me the following error while I compile Scintilla:
![image](https://user-images.githubusercontent.com/90293/120201089-54f73e00-c225-11eb-9c67-3d948a32a3c8.png)

v142 seems work for @sasumner so I guess I'm missing somethings in my installation...

**Comment by donho** [comment]
Here's the other screen shot of settings:
![image](https://user-images.githubusercontent.com/90293/120201801-1f068980-c226-11eb-9ea0-412681187b07.png)

**Comment by donho** [comment]
@mere-human 
Indeed, Toolset **v141** DOES make my Notepad++ built under VS2019 !

> change Platform Toolset (as @mere-human mentions) -- but I don't install v141, I just change the setting to v142

Apparently, the VS2019 of @sasumner is a sort of  Super Deluxe Edition which does more things than my VS2019 Community Edition. I used default Toolset v142 of  VS2019 Community Edition and that produce the built error in above screenshot!!

> change Treat Warnings As Errors to No

OTOH, I keep the current warning level unchanged. I built 3 platforms (32/64/ARM64) in release successfully!

Thank you guys for your help!

@chcg 
Should we worry about Toolset v142 in the future or there are other workaround solutions?

**Comment by sasumner** [comment]
> Super Deluxe Edition

It's:
```
Microsoft Visual Studio Enterprise 2019
Version 16.4.3
```

**Comment by vladkosi** [comment]
Add `#include <string>` to fix those errors.

**Comment by mere-human** [comment]
> I suppose that you install VS2019 upon your VS2017?

No, I have just VS2019.
Maybe, you needed to install individual components by running the installer again.
Anyway, I see that it works now for you which is great!

By the way, here is my version:
Microsoft Visual Studio Community 2019
Version 16.10.0

**Comment by chcg** [comment]
@donho I think we should go for v142 as this is the default platform toolset for VS2019

https://github.com/notepad-plus-plus/notepad-plus-plus/pull/7565
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5536

**Comment by luizfernandonb** [comment]
> What I do (and what I've always done since I never had VS2017):
> 
> * change _Platform Toolset_ (as @mere-human mentions) -- but I don't install v141, I just change the setting to v142
> * change _Treat Warnings As Errors_ to _No_
> 
> Perhaps if I'd ever installed v141, I would not have had to change the warnings-as-errors setting?
> 
> Note: My VS2019 is NOT a "free" edition.

How do you do this: `change _Platform Toolset_ (as @mere-human mentions) -- but I don't install v141, I just change the setting to v142`?

If I didn't install v141, how can I switch to v142 if it comes as standard?

**Comment by adzm** [comment]
I also created a .editorconfig that enforces notepad++ conventions (braces on newlines etc) automatically so you don't have to mess with global defaults. Would be great to have this build in 2019 without the 2017 toolset.
