### ISSUE TITLE
Prefix Tooltips with their Function key

### ISSUE THREAD

**Issue by blinkok** [notepad-plus-plus/notepad-plus-plus#9924]
### Description of the Issue
Currently the tooltip for the Open file button is "Open". It would be great if the tool tip was prefixed with the shortcut key description to help educate the user on shortcuts. So the "Open" tooltip would become "Ctrl+O Open".

### Steps to Reproduce the Issue
Mouse over the "Open" toolbar button. 

### Expected Behavior
It would be good to see "Ctrl+O Open"

### Actual Behavior
Currently it displays "Open"

**Comment by sasumner** [comment]
It's enough that it is on the _File_ menu entry for _Open..._
