### ISSUE TITLE
[FR] Please add "Cancel All" button next to "Cancel" button on file "Save As" dialog window

### ISSUE THREAD

**Issue by tonedef71** [notepad-plus-plus/notepad-plus-plus#9931]
### Description of the Issue

I am one of those people who has hundreds of open file tabs in the NotePad++ application.  A large percentage of those open file tabs are untitled "works in progress".  I am also a klutz; sometimes I accidentally click the "Save All" button instead of the "Save" button.  When that happens and I have several hundred open file tabs which are still untitled "works in progress" and not yet ready to be committed to hard disk, I am inundated with a long queue of back-to-back "Save As" file dialogs.  I would be eternally grateful if functionality could be added to the "Save As" file dialog window which does the following:

1.  Recognizes that it is not a single file but a whole queue of pending files to be saved.
2.  When so recognized, a "Cancel All" button is added to the dialog window next to the existing "Cancel" button.  
3.  When the Cancel All" button is clicked, the current file "save as" operation and all pending file "save as" operations are immediately bypassed and purged from the pending event queue.

This new feature would spare me from cursing at myself and suffering the burden of holding down the "Esc" key for several minutes in order to dismiss the barrage of pop-up "Save As" dialog windows.

Thank you in advance for your time and consideration.

### Steps to Reproduce the Issue

1.  Create a lot of new files (about a hundred or so, to appreciate the struggle).
2.  Click the "Save As" button in the toolbar.
3.  Sigh loudly while holding down the "Esc" key on the keyboard for as long as it takes for all of the file "Save As" dialogs to stop popping up.

### Debug Information

Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1556
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NavigateTo.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll 

![NotePad++FeatureRequest](https://user-images.githubusercontent.com/3978924/120402059-4422f700-c30f-11eb-89a5-604943303780.png)

**Comment by MarkusBodensee** [comment]
What about dirty files, which are already present on disc? Should the save process for them be canelled, too?

I this case, the "Cancel All" option does not work, because the dialogue only pops up if unsaved files are present. Additionally, I think, it cannot be ensured that the dialogue for an unsaved file pops up first, before other files are already saved.

**Comment by tonedef71** [comment]
> What about dirty files, which are already present on disc? Should the save process for them be cancelled, too?

Yes, the "Save All" process should be cancelled for the dirty files as well.  


> In this case, the "Cancel All" option does not work, because the dialogue only pops up if unsaved files are present. Additionally, I think, it cannot be ensured that the dialogue for an unsaved file pops up first, before other files are already saved.
> 
> Or otherwise, if dirty files get saved, a "Cancel All" could be against user expectation.

The purpose of the "Cancel All" is **_not_** to give up on the file changes and restore modified files to their previously-unmodified state.  The purpose is to simply cancel the user's (inadvertent) click of the "Save All" action button; dirty files should remain dirty (i.e. the modified works-in-progress files will remain as modified works-in-progress).

This is how clicking the "Cancel" button on the "Save As" dialog works today with respect to an individual file; the file remains dirty (a modified, work-in-progress).  There exists a separate menu action "File -> Reload from disk" if the user actually wants to revert changes made to a file (and that is a different use case from what I am presented in this enhancement request).

**Comment by tonedef71** [comment]
Regarding the proposed fix (the Confirm Save all dialog)... this solution provides one (and only one) opportunity to stop the mass save of all modified unnamed files.  The "Cancel All" button suggestion I proposed -- while more challenging to implement -- provides the user the opportunity to dispense with the mass save with every dialog prompt.  For example, five saves into a queue of a few hundred modified files, the user realizes that they do not wish to continue confirming or canceling the saving of all modified files that are pending.  It is good to have that opportunity to interrupt the "Save All" process without having to resort to holding down the Escape key to dismiss all of the "Save As" dialogs for the unnamed, modified files.
