### ISSUE TITLE
Maximised on second monitor, the top of the title bar is one pixel below the top of the screen

### ISSUE THREAD

**Issue by pjc50** [notepad-plus-plus/notepad-plus-plus#9933]
### Description of the Issue
Maximised on second monitor, the top of the title bar is one pixel below the top of the screen. This causes misclicks selecting whatever application is maximised below Notepad++ when trying to focus Notepad++.

### Steps to Reproduce the Issue

1. Dual monitor setup; monitor 1 is 150% scale, monitor 2 is 100% scale. Monitor 2 is 2880x1632 and positioned to the left and slightly above monitor 1, resulting in negative window coordinates
2. On monitor 2, have Notepad++ maximised on top of another window (e.g. Mozilla, Visual Studio)
3. Move mouse to top of screen and click on title bar

### Expected Behavior
Focus notepad

### Actual Behavior
Focus the window below

### Debug Information
Notepad++ v7.6   (32-bit)
Build time : Nov 12 2018 - 23:51:42
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : none

I confirmed the issue with Spy++. Working windows have a "Rectangle" of (-2880, -170)-(0,1462). Notepad++ has a Rectangle of (-2891, -169)-(11,1473), putting its top just below the top of the screen. This is going to be something horrible with non-client draw areas, isn't it?

**Comment by sasumner** [comment]
Closing; let's make #8660 the controlling issue on this.
