### ISSUE TITLE
FluentUI icons - include icon for unmodified files

### ISSUE THREAD

**Issue by adzm** [notepad-plus-plus/notepad-plus-plus#9937]
The blank space looks so strange. I know there was some concern about a disk icon that could be distinguished between unsaved and saved without colors. Perhaps we could reuse another icon instead? Even something simple like a circle could indicate its status.

**Comment by sasumner** [comment]
>concern about a disk icon

Diskette icons are so 1990s -- can't we get away from that somehow?
Clearly I understand that a lot of programs use these still...but...sigh.
A great deal of computer users these days don't even know what a diskette is (was).

>something simple like a circle could indicate its status.

A circle conveys no meaning.
The "alternate" icons set uses a checkmark, which at least has some connotation attached to it:

![image](https://user-images.githubusercontent.com/30118311/120634540-5ef18a80-c439-11eb-8d76-4af65f2b30b7.png)

**Comment by donho** [comment]
I do understand (and agree with) the approach of @WildByDisgn - if the file is clean and on its normal state, the indicated icon is not necessary. Let's see users' reaction after the release of v8. The unmodified indicator will be add if the request is coming strongly.

**Comment by sasumner** [comment]
>The blank space looks so strange.

Probably the answer is No, but...  Is it possible/reasonable to shift a tab's text to the left to take up the empty space for this case?  Then it wouldn't look so strange.

**Comment by cpolychronidis** [comment]
How about a diskette icon for unmodified files and a diskette with a pencil on it for modified files in order to indicate that something has been written?

**Comment by donho** [comment]
@sasumner 
>  Is it possible/reasonable to shift a tab's text to the left to take up the empty space for this case? Then it wouldn't look so strange.

Why not? But not right now: There are a lot of change in v8 from v7.9.5, so we should focus (IMO) on stabilizing the new version.    
And BTW, it's easier to maintain with an empty icon, so let's see what users say about it.
