### ISSUE TITLE
Append extension doesn't work in Save As dialog

### ISSUE THREAD

**Issue by mere-human** [notepad-plus-plus/notepad-plus-plus#9939]
### Description of the Issue

This was originally reported on the Community Forum https://community.notepad-plus-plus.org/post/66533
Thanks to @pryrt  and Alan Kilborn for providing details and @sasumner for testing.
Some discussion was in https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9732.

### Steps to Reproduce the Issue

1. Press _Ctrl+N_ to create new file; new1 tab appears
2. Press _Ctrl+Alt+S_ to invoke Save As dialog
3. Check the Append extension checkbox:
![image](https://user-images.githubusercontent.com/9664141/120615347-db4b9400-c460-11eb-84fd-bea792956dd5.png)
4. Set the file name to anything without extension (e.g. `z`):
![image](https://user-images.githubusercontent.com/9664141/120615404-eacadd00-c460-11eb-8e87-26add1ff9182.png)
5. Click on _Save_ button using left mouse button

### Expected Behavior

File is saved with extension as `z.txt`

### Actual Behavior

File is saved without extension as `z`

Note:
In step 5 if mouse click is replaced by
* _Enter_ key - works as expected (.txt extension added automagically)
* _Alt+S_ - doesn't work (no extension added)

### Debug Information

Notepad++ v8   (64-bit)
Build time : May 27 2021 - 22:10:00
Path : E:\Installs\npp\npp.8.0.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.985
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by mere-human** [comment]
I have a fix, will do a PR after testing it.

**Comment by donho** [comment]
@mere-human 
OK, great.
I can reproduce on `button-click`, `ENTER` & `ALT+S`.
I will do Notepad++ v8 RC3 this afternoon, hope this PR could be on time for Notepad++ v8

**Comment by donho** [comment]
@mere-human 
I don't wanna push you, just I'm about to package Notepd++ v8 RC3.
Is the fix ready to be merged or it's better to wait for integrating it in the next version?

**Comment by mere-human** [comment]
@donho I'll push it today in a couple of hours.
I think, it's better to do it for current version rather than next one.

**Comment by donho** [comment]
Sorry, v8 RC3 is out:
https://community.notepad-plus-plus.org/topic/21273/notepad-v8-release-candidate-3

If there are some critical bugs found in RC3, I'll be able to include the fix by rebuild RC4 or release 8.
Otherwise it's not a critical, we can integrate it in v8.1. So take you time.
