### ISSUE TITLE
FunctionList not work with userDefinedLangName

### ISSUE THREAD

**Issue by codedeep** [notepad-plus-plus/notepad-plus-plus#994]

**Comment by tomas-chrastina** [comment]
Hi, it's working for me in **v6.8.3**. Try to be more specific. Paste your ``%APPDATA%\Notepad++\functionList.xml``, and some more info how to reproduce this.

As far as I tested, only definition of association by file extension ``ext`` is NOT working.

**Comment by MetaChuh** [comment]
insufficient information provided
