### ISSUE TITLE
New instance window doesn't show the Doc Switcher

### ISSUE THREAD

**Issue by wisemike2** [notepad-plus-plus/notepad-plus-plus#9941]
### Description of the Issue
New window doesn't show the Doc Switcher, although the original NP++ instance has it opened.

### Steps to Reproduce the Issue

1. Alt + F6 (to open new instance).
2. It opens without the "Doc Switcher" bar to the left.
3. Then I open Options > General > Document switch panel > Show (so it shows).

### Expected Behavior
Show the same options and preferences as the main instance of NP++

### Actual Behavior
It opened without the Doc Switcher

### Debug Information

Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1023
Current ANSI codepage : 1256
Plugins : ComparePlugin.dll Explorer.dll HTMLTag_unicode.dll mimeTools.dll NppConverter.dll NppExport.dll NppFavorites.dll NppTextFX.dll NppToolBucket.dll PythonScript.dll RegexTrainer.dll _CustomizeToolbar.dll

**Comment by sasumner** [comment]
>Alt + F6 (to open new instance).

Just some notes:
Alt+F6 is designed to open a pathname that is selected in the text to open in a new instance.
With no selection it opens a new instance with a single `new 1` tab.

>Show the same options and preferences as the main instance of NP++

The fact that it doesn't open with the same "stuff" is by-design.

Another example:

- Close all running instances
- Restart one instance
- Open the _Function List_ panel and the _Project 1_ panel (via commands on the _View_ menu).
- Close Notepad++
- Restart
- See that the _Function List_ panel and the _Project 1_ panel being open is remembered
- Start a new instance (via Alt+F6 if you like)
- Observe no _Function List_ panel and the _Project 1_ panel

**Comment by ArkadiuszMichalski** [comment]
@wisemike2 You can try run NPP with `-multiInst` argument, but it will keep only those panels that were remembered the last time when you close the program (changes to the current state will not be taken into account).
