### ISSUE TITLE
Quoted Variables Are Not Highlighted In Bash Scripts

### ISSUE THREAD

**Issue by opticyclic** [notepad-plus-plus/notepad-plus-plus#995]
Create a variable and use it in a command and the variable is highlighted in Orange.
Quote the variable and it turns grey.
e.g. $DATE is Orange on line 3 but Grey on line 4

    #!/bin/bash
    DATE=$1
    mkdir $DATE
    FILENAME="$DATE".zip

**Comment by linquize** [comment]
Seems like Scintilla problem.
![scite](https://cloud.githubusercontent.com/assets/791115/10309548/c3239124-6c6f-11e5-986c-87f9d7f6f1a0.png)

**Comment by donho** [comment]
@linquize You're right about it.
@opticyclic Please report this bug to Scintilla project.

**Comment by opticyclic** [comment]
Reported to Scintilla here https://sourceforge.net/p/scintilla/bugs/1767/
