### ISSUE TITLE
Text direction per tab

### ISSUE THREAD

**Issue by masalha-alaa** [notepad-plus-plus/notepad-plus-plus#9950]
When you switch the text direction via **View > Text Direction LTR / RTL**, or by **Ctrl Alt L / R**, the text direction changes for all the tabs instead of changing only for the active tab.

I think it would be better if it worked tab-wise, because if I have tabs with multiple languages open, I would want each of them to be displayed in a certain direction.

**Comment by rltpoa** [comment]
Yes... Text Direction Per Tab! 
I'm learning Arabic now and I miss this feature. I'm sure I'll also miss it when I learn Hebrew and Persian too.

**Comment by Elsme2256** [comment]
Jj

**Comment by rltpoa** [comment]
So... it looks like the issue was not completed, because donho's PR wasn't merged.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14385#issuecomment-1837511573
If you find any bug, create issues then I'll fix it.
