### ISSUE TITLE
Some buttons have invisible icons

### ISSUE THREAD

**Issue by FlightMS** [notepad-plus-plus/notepad-plus-plus#9959]
With the new fluent UI icons activated, some are still missing and look invisible

![image](https://user-images.githubusercontent.com/82420268/121024001-183ac200-c7a4-11eb-804b-f51719363aba.png)

**Comment by chuv1** [comment]
Same story here
![image](https://user-images.githubusercontent.com/13127366/122024445-1b036b80-cdd1-11eb-9606-f9b69856408d.png)

**Comment by KnIfER** [comment]
It (plugin **non-standard** icons) wasn't suported before...

**Comment by 2epeat** [comment]
> It (plugin **non-standard** icons) wasn't suported before...

In this case, the non-standard icons should remain unchanged.

**Comment by KnIfER** [comment]
@FlightMS What is the "abc" icon in the first image?

**Comment by CennoxX** [comment]
> 
> 
> @FlightMS What is the "abc" icon in the first image?

@KnIfER It's [DSpellCheck](https://github.com/Predelnik/DSpellCheck).

**Comment by CennoxX** [comment]
Workaround: use the [Customize Toolbar Plugin](https://sourceforge.net/projects/npp-customize/), remove all hidden Icons and add all missing Icons as Custom Buttons.
