### ISSUE TITLE
function after class，can not display in function list.

### ISSUE THREAD

**Issue by kyzrong** [notepad-plus-plus/notepad-plus-plus#9965]
### Description of the Issue

function after class，can not display in function list.
### Steps to Reproduce the Issue
language:python
version:7.9.1
such as :
##########################
`#coding:utf-8

class test:
    def __init__(self):
        pass

def fun1():
    pass

def fun2():
    pass`
########################
then,fun1 will not display in the function list.

**Comment by sasumner** [comment]
From Notepad++ 8.0:

![image](https://user-images.githubusercontent.com/30118311/121106072-4a174d00-c7d3-11eb-8bea-4ab4589dd3b3.png)
