### ISSUE TITLE
Don't ask "do you want to reload it" when quitting Notepad++

### ISSUE THREAD

**Issue by nerdfever** [notepad-plus-plus/notepad-plus-plus#9974]
### Description of the Issue

There's really no need to check if the file being edited has been updated by another process when exiting Notepad++.

Nobody really cares, and the need to choose "Yes" or "No" if it has been updated is pointless.

When quitting np++, the program checks if the foreground file (at least; maybe others too) has been updated by another process before exiting.

If it has indeed been updated by another process, np++ pops up a "Reload" dialog box that says "The file has been modified by another program. Do you want to reload it?".

This is a helpful behavior if the user is going to keep running np++.

It's completely pointless if the user has already pressed the close button [X].

Don't do that.

### Steps to Reproduce the Issue

1.  Start NP++
2.  Load a file for editing.
3.  Select some program other than NP++ (just the Windows desktop is fine).
4. Wait for another process to write to the file.
5. Close NP++ by clicking on the close [X] button in the top right of the NP++ window.

### Expected Behavior

I expect NP++ to quit. 

If the file was modifed by NP++ and the user hasn't saved those edits, I expect a dialog box to pop up.

If the file WAS NOT modifed by NP++ and there are no unsaved edits, I expect NP++ to quit. Silently.

### Actual Behavior

A "Reload" dialog box that says "The file has been modified by another program. Do you want to reload it?".

![image](https://user-images.githubusercontent.com/9833299/121273506-6def9700-c896-11eb-8139-ab3aad7b238d.png)

### Debug Information

Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : C:\Program Files (x86)\Notepad++\Notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.985
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
Please search for duplicates before creating new issues.
