### ISSUE TITLE
Auto-Completion (Word-Completion) is very slow in v8

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#9975]
### Description of the Issue 
Auto-completion (Word completion only) is too slow to use - If the word list is long, the box takes 2-3 minutes to appear.

### Steps to Reproduce the Issue

1. Make the text file of 5-6 MB,
2. open in v8. 
3. Set the following settings:
![image](https://user-images.githubusercontent.com/90293/121278654-5da9dd00-c8d3-11eb-9e66-66555acbd0d6.png)
4. Type a character

### Expected Behavior
The Auto-completion box appears immediately.

### Actual Behavior
If the word list is long, the box takes 2-3 minutes to appear 

### Debug Information
Notepad++ v8   (64-bit)
Build time : Jun  6 2021 - 18:38:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19042.985
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by donho** [comment]
@chcg 
I thought this regression comes from 1 of 2 fixes (da352ef5ad9cec2e6b6c51b0271e43d65b92a3f3 & 70762b1a0302d6b656ae22be36f6d997b3be0c6b) of auto-completion. But after reverting both commits, the auto-completion performance issue persists.

I then checkout [One button to compile them all](ab58c8ee3ed1b8f8fa84a06c0f7d304fb0f0cd76) and compiled binary has still the auto-completion performance issue. But when I checkout the commit [Fix Copy command in Search result is available as there's no selection](9c66ff9c71e12a4c18c7b02e8c221002af27560d) - the previous commit of `One button to compile them all`, compile it and run it with SciLexer.dll of v7.9.5 - the issue is gone.

So obviously the static link has introduce the auto-completion performance issue (maybe due to some compile options?), Could you do some investigation please?

**Comment by ArkadiuszMichalski** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commits/master?after=ea8c9779c21b4ef9b1736fa54e4135063a43185b+69&branch=master

Commits on Apr 17, 2021
Remove SciLexer.dll from the packaging
One button to compile them all …

Commits on Apr 16, 2021
[Fix Copy command in Search result is available as there's no selection](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/9c66ff9c71e12a4c18c7b02e8c221002af27560d)

**Comment by donho** [comment]
@ArkadiuszMichalski 
I don't really get what you tried to say in your comment. Do you mind to elaborate it?

**Comment by donho** [comment]
@ArkadiuszMichalski 
NM, got you.

**Comment by mere-human** [comment]
I recorded some profiling of the autocomplete process.
Here is what I got.
![image](https://user-images.githubusercontent.com/9664141/121433742-12500700-c985-11eb-84cd-8c4663e1c1e8.png)
---
![image](https://user-images.githubusercontent.com/9664141/121433751-167c2480-c985-11eb-8b2d-39af09e5f878.png)
---
So it seems it's in Scintilla.
Does it ring a bell?
I'll continue investigating tomorrow.

**Comment by mere-human** [comment]
@chcg Do we compile Boost Regex as a part of SciLexer VS project? 
I wonder if we don't pass some important flag/define to it which causes this slowdown.
I'm looking at this:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ab58c8ee3ed1b8f8fa84a06c0f7d304fb0f0cd76#diff-85b945d8756c8223885ade8c8ca88409d2eed9459504dc93eed690d65137ae6f

**Comment by mere-human** [comment]
Another observation: I tried Notepad++ MinGW build and it doesn't have such problem.
Sure, there is a delay when I type, but it's within 1 sec vs 10 sec delay in the regular build.
So, I'm more inclined towards some wrong/missing compiler options.

Here is the test file, just in case:
[lorem.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6629497/lorem.txt)
I usually type "a", "b", "c", etc.

**Comment by chcg** [comment]
What changed (in the consider order of relevance):
- build now uses https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/win32/SciLexer.vcxproj instead of https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/win32/scintilla.mak (as @mere-human didn't observer the issue with mingw I would consider to search in the compiler/linker settings of the VS project first, maybe even N++ VS project needs to be taken into consideration as the static lib is linked into the N++ executable)
with nmake and scintilla.mak libscilexer.lib could be compiled and linked with N++ instead of the SciLexer.vcxproj to check this
- integration between N++ and scintilla changed from dll to static lib
- boost version with major change to header only lib

**Comment by mere-human** [comment]
@chcg What if we build SciLexer using same old makefile but from Visual Studio? 
That is we still have SciLexer project in VS, we can navigate files, etc.
But during build, VS invokes NMake.
This way no wrong defines/flags would sneek in.

There is a `NMakeBuildCommandLine` tag that is supported by VCXPROJ exactly for that purpose.
I haven't found the documentation for it yet. But I've seen it being used in other projects.
For example:
https://github.com/spevans/apple-icu/blob/6bd458bec0d2df9c8540335ef755bb37ff77dcca/icuSources/data/makedata_uwp.vcxproj#L51

**Comment by nbred5** [comment]
It look like it is regex search, try \<a(\w+) in Mark  and then Mark All, takes quite a while, a lot longer than versions pre 8.0

**Comment by mere-human** [comment]
Here is Visual Studio NMake project documentation:
https://docs.microsoft.com/en-us/cpp/build/reference/creating-a-makefile-project?view=msvc-160
https://docs.microsoft.com/en-us/cpp/build/reference/nmake-property-page?view=msvc-160
It describes how to setup it using GUI wizard.
However, the same is possible when manually editing the .vcxproj.

**Comment by ArkadiuszMichalski** [comment]
>@mere-human 
Another observation: I tried Notepad++ MinGW build and it doesn't have such problem.
Sure, there is a delay when I type, but it's within 1 sec vs 10 sec delay in the regular build.
So, I'm more inclined towards some wrong/missing compiler options.
Here is the test file, just in case:
lorem.txt
I usually type "a", "b", "c", etc.

I can confirm that, MinGW on actual code is slightly slower than the 7.9.5 release (1s vs 3s). But release 8 is tragic in that aspect (15s). Anyway, this change is making a visible regression even for MinGW.

**Comment by chcg** [comment]
@mere-human I did a test with https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/39519260/job/vskj9sw80jbxn98r/artifacts -> Notepad++.mingw.Release.exe and there I also see the slowdown. With which version did you tested it? Thanks @ArkadiuszMichalski  for the confirmation
- doing the libscilexer build by nmake doesn't change the behaviour
- Building the project with compiler option to favor for speed doesn't help.

**Comment by mere-human** [comment]
> With which version did you tested it?

I tested with the same exact version as you did.
Sure, there is a slowdown in MinGW build. But it is 2-3 seconds. In regular build it's about 10 seconds.

**Comment by donho** [comment]
> boost version with major change to header only lib

@chcg has just pointed out an eventual cause: **boost** - it's the one major change in the commit in question.
I wonder if we can keep current VS structure (notepad++ & SciLexer) but include boost regexpr lib instead of all boost regex header files. 

@chcg Could you please try this option please (with a PR) ?

**Comment by chcg** [comment]
- Building N++ against dll again and combining with one from 7.9.5 vs 8.0 already shows up with the slowdown. So most likely it is the boost lib which causes the problems.
- I think we had this option during the development of the PR that boost was taken from a external path. I will have a look at that.

**Comment by MarkusBodensee** [comment]
Is there a way to contact the boost regex developers and ask them which compiler flags should be used? Or even just to ask them if they know about a regression of the header only lib?

Force inlining with [/Ob](https://docs.microsoft.com/en-us/cpp/build/reference/ob-inline-function-expansion) could be an option to speed up and without using the [/O2](https://docs.microsoft.com/en-us/cpp/build/reference/o1-o2-minimize-size-maximize-speed) hammer. It would be a shame if the header only lib must be reverted, because it is such a nice thing to have.

**Comment by MarkusBodensee** [comment]
Oh, what I just found:

Release Build of SciLexer sets `Optimization` to `MinSpace` (all 3 Release Builds):
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/ea8c9779c21b4ef9b1736fa54e4135063a43185b/scintilla/win32/SciLexer.vcxproj#L146

Whereas Release Build of notepadPlus sets `Optimization` to `Full` (all 3 Release Builds):
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/ea8c9779c21b4ef9b1736fa54e4135063a43185b/PowerEditor/visual.net/notepadPlus.vcxproj#L302

I think `MinSpace` is good for (of course) minimal size, but could slow down execution time significantly. Maybe this is a problem? Can someone test this, unfortunately I cannot do it by myself at the moment.

**Comment by donho** [comment]
Just revert [One button to compile them all …](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ab58c8ee3ed1b8f8fa84a06c0f7d304fb0f0cd76) on my local branch:
[bin64.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6637518/bin64.zip)

The test result confirms it's due to this PR.

**Comment by donho** [comment]
@MarkusBodensee 
> I think MinSpace is good for (of course) minimal size, but could slow down execution time significantly. Maybe this is a problem? 

"I have tried different compiling/linking optimization options with both Notepad++ project & Scilexer project in VS, but without remedying the problem."

ref:
https://community.notepad-plus-plus.org/topic/21283/notepad-v8/20?_=1623405886680

**Comment by ArkadiuszMichalski** [comment]
>@MarkusBodensee 
Is there a way to contact the boost regex developers and ask them which compiler flags should be used?

Maybe it's worth just opening an issue? If that's known and there is a solution, at least they should  put the solution somewhere in the FAQ. 
https://github.com/boostorg/boost

**Comment by donho** [comment]
@chcg 
Could the PR in question be done in a few days? I don't wanna push, just because it's quite critical issue.
In the case that you have no time yet to do it, there's no problem, I can do it. Please let me know.

**Comment by chcg** [comment]
Already on switching to static build the slowdown happens, see https://github.com/chcg/notepad-plus-plus/tree/appveyor_boost_static -> https://ci.appveyor.com/project/chcg/notepad-plus-plus/build/job/u342g6a3xa5n80hx/artifacts. It is strange that also on changing the current master build with boost 1.76 back to dynamic lib is showing that slowdown even on nmake builds.

**Comment by donho** [comment]
@chcg 
Could you do it as a PR so I can test on my side please?

**Comment by donho** [comment]
> Edit: To make sure we are on the same page, my idea is to remove boost regexpr heaaders (v1.76) only and use the older version of boost regexpr static lib (boost_1_69_0) that we build

I guess it (using old boost regexpr static lib instead of boost regexpr heaaders v1.76) will fix the reg search performance issue. But if it doesn't, then we have to revert the whole commit - I've tested it locally and [it fixes the performance issue](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9975#issuecomment-859464972).

**Comment by ozone10** [comment]
I've just removed `SCI_OWNREGEX` from

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/467870d66e0f4e3151cfeb9d93c0522d058f7eb0/scintilla/win32/SciLexer.vcxproj#L76

which means it will use built-in regex implementation, so it should fix this issue.

**Comment by mere-human** [comment]
> built-in regex implementation, so it should fix this issue.

I'm afraid that built-in regex isn't that feature-rich as the one from Boost. Which will lead to even more amount of complaints.
This is one of the reason I like Notepad++. For example, Visual Studio sometimes doesn't handle some regexes well and gives weird results.

**Comment by donho** [comment]
It's problematic with boost's regex.
but it can pass the build test in this PR:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10001

It can be considered as a solution. Otherwise no.

**Comment by donho** [comment]
@mere-human 
> I'm afraid that built-in regex isn't that feature-rich as the one from Boost. Which will lead to even more amount of complaints.
This is one of the reason I like Notepad++. For example, Visual Studio sometimes doesn't handle some regexes well and gives weird results.

could you provide me an RegEx which works with boost's RegEx engin but not on Scintilla's one ?

**Comment by ozone10** [comment]
> 
> I'm afraid that built-in regex isn't that feature-rich as the one from Boost. Which will lead to even more amount of complaints.
> This is one of the reason I like Notepad++. For example, Visual Studio sometimes doesn't handle some regexes well and gives weird results.

You are right, wanted to write "could" instead of should

> could you provide me an RegEx which works with boost's RegEx engin but not on Scintilla's one ?

maybe this `\((?>[^()]|(?R))*\)` , select everything in bracket

**Comment by donho** [comment]
@ozone10 
Indeed!

**Comment by mere-human** [comment]
> could you provide me an RegEx which works with boost's RegEx engin but not on Scintilla's one ?

No, I can't come up with a concrete example. But I'm pretty sure guys from the Community Forum can. You just have to provide them a build without Boost Regex.

**Comment by mere-human** [comment]
I've just changed SciLexer.vcxproj to use the previous version of Boost.Regex 1.70 that was provided as a static library.
Unfortunately, it doesn't help. I still see a slowdown.
What I did:
- `INCLUDES=$(INCLUDES) -Ie:\Development\boost_1_70_0\` in `notepad-plus-plus\boostregex\nppSpecifics.mak`
- `..\include;..\src;..\lexlib;e:\Development\boost_1_70_0\` in Additional Include Directories for `SciLexer.vcxproj`
- `libboost_regex-vc141-mt-s-x64-1_70.lib` in Linker > Input > Additional Dependencies  for `Notepad++.vcxproj`
- Rename `boostregex` => `_boostregex` in `\notepad-plus-plus\boostregex\` just to be sure

I could have missed something.
Now, I'm stuck. What could be the reason? Is it the fact that we link with SciLexer static library instead of dll? Is it a combination of different factors?

**Comment by donho** [comment]
@mere-human 
Please make PR so ppl (including me) could see and improve what you did.

**Comment by mere-human** [comment]
> Please make PR so ppl (including me) could see and improve what you have done.

I think it's not needed.
1. It doesn't help. 
2. I described all of my changes in the comment.
3. There is already a PR which may fix the problem.

**Comment by chcg** [comment]
- By removal of the outer change of the locale setting the performance issue seems to be fixed.
- Probably it is not needed as within template compileRegex() this call is also done and probably just once as the settings are not changing during the autocompletion call.
- Still needs to inspected deeper for BoostRegexSearch::SubstituteByPosition()
- It is not completely clear to me why this is just now a problem with the change to static linkage and not already before with SciLexer as own dll. Maybe some multithreading lock issue to set the global variable for locale.

Further checks done:
- OK: current N++ code + switching back to scilexer dll solution + boost 1.69 (the newest available for appveyor 2017)
- NOK: current N++ code + switching scilexer to dll (nmake or vsxproj)  +  boost 1.76
- NOK: old N++ code before PR + changes for static lib + scilexer build via nmake as static lib with boost 1.69

**Comment by xomx** [comment]
> It is not completely clear to me why this is just now a problem with the change to static linkage and not already before with SciLexer as own dll.

I once had a similar issue (changed dynamic link of an otherwise non-problematic library to static, then suffered a specific slowdown), in my case the culprit was different memory handling (the DLL in question used different memory allocation functions (new/delete, malloc/free) than the rest of my code). This was long time ago, so I do not remember details, sorry. So maybe the memory management in the previously separated SciLexer.dll was not influenced from the rest of the n++ code.

**Comment by donho** [comment]
@chcg 
Thank you for the fix!

**Comment by xomx** [comment]
@chcg 

if that fix works maybe combination of my previous explanation with:
https://stackoverflow.com/questions/15216279/global-variables-slow-down-code/15216692
https://stackoverflow.com/questions/7241035/speed-of-accessing-local-vs-global-variables-in-gcc-g-at-different-optimizati
