### ISSUE TITLE
Lets make Icons for accociation files in Notepad style

### ISSUE THREAD

**Issue by Diaskhan** [notepad-plus-plus/notepad-plus-plus#998]
Lets make Icons for accociation files in Notepad style.
I am using Notepad for looong time. I am to sad? that notepad++ has no file icons for JAVA, php,C# and pascal.

Maybe its time for add some beatiful Icons in Notepad style ???

![file-extension-image](https://cloud.githubusercontent.com/assets/15046677/10389334/6d569b90-6e92-11e5-9fdc-5b72475fd359.png)

**Comment by vgturtle127** [comment]
I would be OK with this, I think the default Notepad++ logo would be good, but in place of the chameleon, just put the file extension or language or whatever.
