### ISSUE TITLE
"In selection" option for Find or Replace does not work with "Find next" action (finds/replaces text outside of selected region)

### ISSUE THREAD

**Issue by e-d-n-a** [notepad-plus-plus/notepad-plus-plus#9981]
### Description of the Issue

I recently updated to this latest version and I'm not sure, whether I used this feature successfully with this version yet.
But now I cannot get it to work and it definitely worked before in the last version I had installed (v7.8.x).

### Steps to Reproduce the Issue

1. Open any text file.
2. Select a multiline text region
3. Open "Find" dialog, e.g. via <Ctrl+F>
4. Activate "In selection" option (if not already selected)
5. Use "Find Next" (in Find or Replace) to search for something specified in "Find what"

### Expected Behavior
Find and/or Replace only works in selected text region, when "In selection" is activated.

### Actual Behavior
Works like a normal search and replace.
Finds search word downwards or anywhere (when "Wrap around" is selected) outside the selected region when "Find Next" is pressed!

### Debug Information

Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Home Premium (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll ElasticTabstops.dll HexEditor.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppSnippets.dll NppTextFX.dll Python Indent.dll PythonScript.dll SecurePad.dll SelectQuotedText.dll SessionMgr.dll Tidy2.dll ZenCoding-Python.dll

**Comment by e-d-n-a** [comment]
OK, I noticed now, that there is a grouping box around "In selection" and only 1 or 2 action buttons (see screenshots).
Was that always there? Maybe I stumbled upon that restriction before...

So for "Replace" I'm only able to use the "Replace All" with "In selection" and can confirm that it works!
It would be nice though, if you could step through the search results before making replacements.
But there might be a reason, why this is not offered/working.

![Find](https://user-images.githubusercontent.com/8239937/121369296-02600500-c93c-11eb-8db8-8d678612e6da.png)
![Replace](https://user-images.githubusercontent.com/8239937/121369303-0429c880-c93c-11eb-872b-e022a5a4c93d.png)

**Comment by e-d-n-a** [comment]
I found Issue #9811 now, which is related to this and explains the version changes and UI decisions somewhat.

**Comment by sasumner** [comment]
>there is a grouping box around "In selection" and only 1 or 2 action buttons (see screenshots).
Was that always there?

Yes, always there.

>for (replacing) I'm only able to use the "Replace All" with "In selection" and can confirm that it works!

>if you could step through the search results before making replacements. But there might be a reason, why this is not offered/working.

The reason is that when you use _Find Next_ or _Replace_ buttons to jump to the next match, it uses selecting-of-text to show you where that match is, thus destroying your original selection.  At that point there would be no wider selection to search inside of.  Maybe an awkward explanation but hopefully it makes some sense.
