### ISSUE TITLE
Filename Extension (Save as Type) ignored with File Save As... for new files (XML Language in example)

### ISSUE THREAD

**Issue by SeanPGit** [notepad-plus-plus/notepad-plus-plus#9986]
This may exist for other file types and I am sure is "new behaviour" over older versions of Notepad++ as I've used this sequence many, many times and this week, after an update is consistently showing this behaviour.

### Description of the Issue
When creating a "new" tab, pasting in some content, setting Language, choosing "Save As..." - selecting an EXISTING file and modifying only the "Filename" part only; The file save WITHOUT the "Save as Type" Filename Extension. 
The Extension has to be explicitly added to the "Filename" part. 

### Steps to Reproduce the Issue

1. Create a New file tab
2. Paste in some content - XML in my case
3. Change Language to XML in my case
4. File Save As...  (Dialog shows current files as "Save as Type" - XML in my case).
5. Choose an existing file.
6. Change the filename (new test case in my example)
7. Click Save

### Expected Behavior
The New file should be saved to the new filename - with the Save As Type filename extension - .xml in my case.

### Actual Behavior
The new file is saved with the new filename - but with NO Filename extension, and has to be renamed in Explorer.

After renaming of course - the saved file tab "no longer exists" and has to be "Save As..." again to the now correctly showing file OR explicitly with the filename extension.

### Debug Information
Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.985
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll

**Comment by mere-human** [comment]
@SeanPGit Could you, please, try it using Notepad++ v8?
You can download and check it in portable version, if you don't want to update your local version yet.

**Comment by sasumner** [comment]
I'm interpreting step 6 as "remove all text from the _File name:_ box, and replace with exactly `new test case`.

If that's a good interpretation, Notepad++ 8 gives me a saved name of `new test case.xml`

Note that for my test, the _Append extension_ checkbox was ticked.

But...even though I did it, I'm not sure what relevance step 5 has in the process.

**Comment by SeanPGit** [comment]
> Note that for my test, the Append extension checkbox was ticked.
Ah! after posting, I suspected an "option" somewhere and maybe, just maybe - blindly "turned off"; OR was turned off by an update? I've not "knowingly" changed any such option.
In my v7.x - I cannot see this option in the "Save As..." nor "Settings|Preferences"... so where is it?
I will try v8 as suggested - but quite, quite busy right now documenting my use cases... 

A couple of other nuggets of information which may / may not be of relevance:

- The files in question are, ultimately, on a MS Sharepoint which is "Linked" to in Windows Explorer...
- The overall path+filenames are getting close to the maximums supported
- I know because I've actively had errors when it is exceeded, so "paring down" the filenames to suit...
- However, the documented / tested case - including extension - DOES fit the overall allowance (25x?? characters - too little time to check!).

**Comment by sasumner** [comment]
>but quite, quite busy right now

If you're that busy, why not just type `.xml` on the end of your name and move on?

**Comment by roc3f** [comment]
How to fix the

**Comment by roc3f** [comment]
> @SeanPGit Could you, please, try it using Notepad++ v8?
> You can download and check it in portable version, if you don't want to update your local version yet.

**Comment by SeanPGit** [comment]
> > but quite, quite busy right now
> 
> If you're that busy, why not just type `.xml` on the end of your name and move on?
Yes - of course as a temporary move I have to "remember" to do this; but hard to re-train your brain and fingers for a process which has worked for years, whilst working through 100s of cases a day! 

It is a clear bug in the application, introduced in a recent update; and now behaving in a completely "non-standard" way. Seriously - when was the last time you did "Save as..." in Word / Excel etc. and had to type .docx / .xlsx?

I'll try v8 - but I assume it's a beta as not offered through the Update of the latest version I'm running. (Yes I tried update before reporting!).

**Comment by SeanPGit** [comment]
> > @SeanPGit Could you, please, try it using Notepad++ v8?
> > You can download and check it in portable version, if you don't want to update your local version yet.
Just tried it - it fails in v8 too! 
"Append Extension" is ticked in the "Save As..." box.

**Comment by mere-human** [comment]
Ok, I can confirm the same in v8.
But why does it work fine in my debug build? I'll try to figure out...

**Comment by SeanPGit** [comment]
> I'm interpreting step 6 as "remove all text from the _File name:_ box, and replace with exactly `new test case`.

Actually is is usually "editing" the name a little - rather than wholesale "remove all text"... So "Change" name as I put...

> But...even though I did it, I'm not sure what relevance step 5 has in the process.
Seems important.
If I do the same and just type "new test case" - then I DO end up with a resultant file "new test case.xml".

I've got it!
*IF* I **type** in a name like "09 DCSSCardUpdate RSP2z - CardId 1294674.3, Reorder Card, Inherited+FN+LN+Exp TEST 2", rather than "new test case" - it ends up sans extension.

Hence I rather suspect it has something to do with an overall size of the Fully Qualified filename?

As mentioned - these are saved quite deep into a Sharepoint site - "Linked" through OneDrive so I can browse via Explorer and other tools etc.

BUT it is clear that there are "longer" Filenames in use in the same folder - clearly "acceptable" to the system, but handled differently by Notepad++

Examples of some fully qualified filenames in the folder now:
`C:\Users\xxxxxxxx\OneDrive - TietoEVRY\XX-999999 - XXXX - Web-services 9999\EVRY Docs\Web-services\Ph2 Self-Service\20210609 Re-order Card tests\05 DCSSCardUpdate RSP2d - CardId 1294674.3, Reorder Card, Inherited+FN+LN - ErrorNo 301 Expire Cannot.xml
C:\Users\xxxxxxxx\OneDrive - TietoEVRY\XX-999999 - XXXX - Web-services 9999\EVRY Docs\Web-services\Ph2 Self-Service\20210609 Re-order Card tests\07 DCSSCardUpdate REQ2f - CardId 1294674.3, Reorder Card, Inherited+FN+LN+Exp TEST.xml
C:\Users\xxxxxxxx\OneDrive - TietoEVRY\XX-999999 - XXXX - Web-services 9999\EVRY Docs\Web-services\Ph2 Self-Service\20210609 Re-order Card tests\new test case
C:\Users\xxxxxxxx\OneDrive - TietoEVRY\XX-999999 - XXXX - Web-services 9999\EVRY Docs\Web-services\Ph2 Self-Service\20210609 Re-order Card tests\08 DCSSCardUpdate REQ2f - CardId 1294674.3, Reorder Card, Inherited+FN+LN+Exp TEST
C:\Users\xxxxxxxx\OneDrive - TietoEVRY\XX-999999 - XXXX - Web-services 9999\EVRY Docs\Web-services\Ph2 Self-Service\20210609 Re-order Card tests\09 DCSSCardUpdate RSP2z - CardId 1294674.3, Reorder Card, Inherited+FN+LN+Exp TEST 2`

**Comment by mere-human** [comment]
@SeanPGit I think I know the root of the problem.
Because the name you type contains dot `.` Notepad++ thinks it is the extension and doesn't add one.

**Comment by SeanPGit** [comment]
> @SeanPGit I think I know the root of the problem.
> Because the name you type contains dot `.` Notepad++ thinks it is the extension and doesn't add one.
Aha! Missed that - can change to a hyphen!  :D

**Comment by sasumner** [comment]
>"." is also still an acceptable character "within" a filename

No disputing this.

>For now - I will avoid the "." - but still would be nice to see a fix

I don't think there is going to be a "fix".
If you have some ideas for such a fix, _that doesn't break anything else_ (the key and challenging part), please feel free to share.  One thing to not do is to think it is "simple".

Issues of this ilk relating to extension have been hotly debated in Notepad++ for years.

@mere-human I'm so glad you took over responsibility for such issues from me (when this setting moved to the _SaveAs_ box).  Thank you.

**Comment by mere-human** [comment]
> Aha! Missed that - can change to a hyphen! :D

Good, if that helps.
It's actually hard to guess what _exactly_ wanted in a each particular case when saving a file.
For example, user types the name `main.c` but the file type is `Normal Text (*.txt)`.
Should it be saved as `main.c`? Because `*.c` is the extension for C source files.
Should it be saved as `main.c.txt.`? Because file type is `Normal Text (*.txt)`.
Also, the extension could be registered and well-known to the OS (example: `*.doc`, `*.avi`) or completely unknown (example: `*.abcdef0123`).

Windows built-in Notepad appends `.txt` only if you type something after dot that is not a registered file type.
Example:
- `a.c` saved as `a.c` (known type)
- `a.abc` saved as `a.abc.txt` (not a known type)

We could do similar. But that might be unexpected for somebody else.

I don't see a good way to fit all the needs at once.
If anybody has any ideas, it would be interesting to know.

For example, `Append extension` checkbox could be changed to a dropdown list with some options:
- Append extension always
- Append extension from file type
- Don't append extension
- Don't append extension for known file types

**Comment by mere-human** [comment]
Also, it's actually nice to see people responding to the messages in bug reports and providing additional details😊

**Comment by SeanPGit** [comment]
@mere-human Thanks for "opening my eyes". Dang; now I need to go back through and rename all of my tests in other tools... ;-)

It is of course a difficult "conundrum"... That check for "known, reasonable" extensions may work 99% of time...
Until people like me forget and "inadvertently" end up with something resembling an extension...
So - lesson learned; I will avoid the "." in the middle of the filename - and is the very reason we stopped naming "Document v3.7"(.docx) etc. internally too! preferring "Document v3_7.docx" instead... :)

**Comment by donho** [comment]
So I guess this issue can be closed.
