### ISSUE TITLE
Fix or update instruction for MinGW 32-bit

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#9989]
[This sentence](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/BUILD.md#build-64-bits-binaries-with-gcc) looks insufficient:
> Note 2: For 32-bit build, https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/8.1.0/threads-posix/sjlj/i686-8.1.0-release-posix-sjlj-rt_v6-rev0.7z could be used. The rest of the instructions are still valid.

I'm trying to compile the current code with 32-bit tools but without success. Scintilla passed but Notepad++ not :
```
../src/darkmode/DarkMode.cpp: In function 'void FixDarkScrollBar()':
../src/darkmode/DarkMode.cpp:227:99: error: invalid static_cast from type 'FixDarkScrollBar()::<lambda(HWND, LPCWSTR)>' to type 'fnOpenNcThemeData' {aka 'void* (__attribute__((stdcall)) *)(HWND__*, const wchar_t*)'}
     addr->u1.Function = reinterpret_cast<ULONG_PTR>(static_cast<fnOpenNcThemeData>(MyOpenThemeData));
                                                                                                   ^
mingw32-make.exe: *** [makefile:284: ../src/darkmode/DarkMode.o] Error 1
mingw32-make.exe: *** Waiting for unfinished jobs....
```

Compiling with MinGW 64-bit works fine.

**Comment by chcg** [comment]
Build check via appveyor is just checking with x86_64-8.1.0-posix-seh-rt_v6-rev0 the 64bit build.

**Comment by ArkadiuszMichalski** [comment]
If the 32-bit version will not be validated in the future, maybe add one more sentence that it is not validated and errors may occur? 

Another question, what about with possible compile errors as above? People should report them or not, because they probably won't be fixed, only 64-bit will be important? I set myself these two tools and compile Notepad++ from time to time, but I don't know whether to report bugs for 32-bit or not.

**Comment by chcg** [comment]
32bit is not checked mainly because it isn't preinstalled for the appveyor image used, see https://www.appveyor.com/docs/windows-images-software/#mingw-msys-cygwin. I would still consider it worth fixing also the 32 bit errors.

**Comment by ArkadiuszMichalski** [comment]
@ ivan-u7n
Do you use 32-bit MinGW also? If so then maybe you would look at this issue too?

**Comment by ivan-u7n** [comment]
@ArkadiuszMichalski Although I don't use 32-bit MinGW on a daily basis, I have it installed and I managed to make building Notepad++ with it to work. Moreover I found a workaround to add it to AppVeyor for the build to be checked periodically. (The reason for the workaround is documented in `BUILD.md`.)
