### ISSUE TITLE
Can I build a linux version of Notepad++?

### ISSUE THREAD

**Issue by Otus9051** [notepad-plus-plus/notepad-plus-plus#9990]
I was thinking of building NP++ for Linux, even though its GNU, I wanted to be sure if I can do it.

**Comment by roc3f** [comment]
> I was thinking of building NP++ for Linux, even though its GNU, I wanted to be sure if I can do it.
>

**Comment by roc3f** [comment]
> > I was thinking of building NP++ for Linux, even though its GNU, I wanted to be sure if I can do it.
> > 
> 
>
