### ISSUE TITLE
Disable dark mode won't change back to normal toolbar icons

### ISSUE THREAD

**Issue by nijawang** [notepad-plus-plus/notepad-plus-plus#9992]
When enable dark mode, there are some icons missing.
But the icons won't change back to normal after disable dark mode.
![image](https://user-images.githubusercontent.com/13096965/121635020-26e0ec00-cab8-11eb-8c24-cdf1bc8c5ac2.png)

![image](https://user-images.githubusercontent.com/13096965/121634968-116bc200-cab8-11eb-97ea-1e7568cecb27.png)

**Comment by thomassmith311** [comment]
Icons aren't missing. It seems like your spacing is messed up. Mine looks like this:
![image](https://user-images.githubusercontent.com/19561856/121732657-80e5af80-cac0-11eb-8568-7ea271ed19eb.png)
It's possible to change the spacing in between icons.

The fact that the icons don't change back -- I don't think that this is a bug, though. It's possible to change them back by going to Settings >> Preferences >> General, and then under Toolbar, select the icon scheme you like with the radio buttons.

**Comment by nijawang** [comment]
Thanks for feedback.
I removed all toolbar' spacing icons but there were still many functions without icons.
It looks like these functions do not have fluent UI icons yet.
![image](https://user-images.githubusercontent.com/13096965/121799141-db1b7780-cc5c-11eb-8372-751c27fd4ca8.png)

**Comment by thomassmith311** [comment]
Seems you have two issues. Your first issue on missing icons is also mentioned here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9959

**Comment by WildByDesign** [comment]
I had a look into the Customize Toolbar (CustomizeToolbar.dll) binary file with Resource Hacker, and it appears that many of those additional icons that are missing are actually embedded within the CustomizeToolbar.dll binary.

The problem with that is that I don't believe that the developer of Customize Toolbar released the source code for that plugin which could have allowed us to modify those icons. Also, I don't think that the developer has been active with Customize Toolbar plugin for several years now.

Does anybody have the source code for Customize Toolbar plugin or have any contact with the developer?

**Comment by thomassmith311** [comment]
Your second issue, on icons not changing back, has an issue here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10049
