### ISSUE TITLE
No error message when locked file could not be saved

### ISSUE THREAD

**Issue by chund** [notepad-plus-plus/notepad-plus-plus#9994]
### Description of the Issue

No error message when file could not be saved.

### Steps to Reproduce the Issue

1. have file which is locked by another program
2. start notepad++ in admin mode
3.  open the file and edit
4. save with Ctrl + S or the Symbol bar
5. => no error that the file was not saved (because it is locked by another process)

### Expected Behavior

An Error message, that there was a sharing violation or the file was locked, or whatever Windows gives as error 

### Actual Behavior
File is not saved, no error message.
File still shows as edited (what is OK).

### Debug Information

Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows Server 2016 Standard (64-bit) 
OS Version : 1607
OS Build : 14393.4467
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by chund** [comment]
I fixed this issue in `Notepad_plus::doSave`
Before opening the PR I'd like to ask if it would be desirable to get the error message from Windows.
I see you have the reuse function `GetLastErrorAsString()` available.
Would it be OK to prepend the Windows Error message before error message "FileLockedWarning" which already existed?
We would need to add $STR_REPLACE$\r before all error messages.
What do you think?

**Comment by mere-human** [comment]
> I see you have the reuse function `GetLastErrorAsString()` available.
> Would it be OK to prepend the Windows Error message before error message "FileLockedWarning" which already existed?

As for me, it could be a good idea. The more information the better.
Let's see what others think.
