### ISSUE TITLE
[Feature Request] Add context menu for encoding in status bar

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#9998]
Currently if you want to change encoding you need to go to Encoding menu.
Sometimes I need to change both EOL and encoding so to not move mouse much, I would like to have this feature.

**Comment by sasumner** [comment]
I can't find the issue, but I know this has been suggested and rejected by @donho before.

**Comment by ArkadiuszMichalski** [comment]
This https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5523#issuecomment-517956714?

**Comment by mere-human** [comment]
It seems a bit inconsistent that there is a context menu for line endings in the status bar but not for encoding.

**Comment by sasumner** [comment]
It is inconsistent but it is what the author wants, so that's it.  I'm closing.

**Comment by sasumner** [comment]
BTW, duplicate of #5523

**Comment by sXNA** [comment]
@donho 
Could this be reopened.
